package mybatis.files;

import com.gmzj.entity.CemArticle;
import com.gmzj.entity.CemArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CemArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_article
     *
     * @mbggenerated Thu Nov 10 10:13:33 CST 2016
     */
    int countByExample(CemArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_article
     *
     * @mbggenerated Thu Nov 10 10:13:33 CST 2016
     */
    int deleteByExample(CemArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_article
     *
     * @mbggenerated Thu Nov 10 10:13:33 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_article
     *
     * @mbggenerated Thu Nov 10 10:13:33 CST 2016
     */
    int insert(CemArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_article
     *
     * @mbggenerated Thu Nov 10 10:13:33 CST 2016
     */
    int insertSelective(CemArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_article
     *
     * @mbggenerated Thu Nov 10 10:13:33 CST 2016
     */
    List<CemArticle> selectByExample(CemArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_article
     *
     * @mbggenerated Thu Nov 10 10:13:33 CST 2016
     */
    CemArticle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_article
     *
     * @mbggenerated Thu Nov 10 10:13:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") CemArticle record, @Param("example") CemArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_article
     *
     * @mbggenerated Thu Nov 10 10:13:33 CST 2016
     */
    int updateByExample(@Param("record") CemArticle record, @Param("example") CemArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_article
     *
     * @mbggenerated Thu Nov 10 10:13:33 CST 2016
     */
    int updateByPrimaryKeySelective(CemArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_article
     *
     * @mbggenerated Thu Nov 10 10:13:33 CST 2016
     */
    int updateByPrimaryKey(CemArticle record);
}