package mybatis.files;

import com.gmzj.entity.CemType;
import com.gmzj.entity.CemTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CemTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_type
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    int countByExample(CemTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_type
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    int deleteByExample(CemTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_type
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_type
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    int insert(CemType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_type
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    int insertSelective(CemType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_type
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    List<CemType> selectByExample(CemTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_type
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    CemType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_type
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    int updateByExampleSelective(@Param("record") CemType record, @Param("example") CemTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_type
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    int updateByExample(@Param("record") CemType record, @Param("example") CemTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_type
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    int updateByPrimaryKeySelective(CemType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cem_type
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    int updateByPrimaryKey(CemType record);
}