package mybatis.files;

import com.gmzj.entity.Zone;
import com.gmzj.entity.ZoneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    int countByExample(ZoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    int deleteByExample(ZoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    int insert(Zone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    int insertSelective(Zone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    List<Zone> selectByExample(ZoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    Zone selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    int updateByExampleSelective(@Param("record") Zone record, @Param("example") ZoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    int updateByExample(@Param("record") Zone record, @Param("example") ZoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    int updateByPrimaryKeySelective(Zone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zone
     *
     * @mbggenerated Fri Oct 07 20:18:55 CST 2016
     */
    int updateByPrimaryKey(Zone record);
}