package com.gmzj.entity;

import java.util.Date;

import com.gmzj.entity.Cemetery.ComStat;
import com.gmzj.entity.Cemetery.ComType;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.id
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.title
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.type
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.content
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.time
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.img_url
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.num
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.author
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.status
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.id
     *
     * @return the value of t_article.id
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.id
     *
     * @param id the value for t_article.id
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.title
     *
     * @return the value of t_article.title
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.title
     *
     * @param title the value for t_article.title
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.type
     *
     * @return the value of t_article.type
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.type
     *
     * @param type the value for t_article.type
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.content
     *
     * @return the value of t_article.content
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.content
     *
     * @param content the value for t_article.content
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.time
     *
     * @return the value of t_article.time
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.time
     *
     * @param time the value for t_article.time
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.img_url
     *
     * @return the value of t_article.img_url
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.img_url
     *
     * @param imgUrl the value for t_article.img_url
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.num
     *
     * @return the value of t_article.num
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.num
     *
     * @param num the value for t_article.num
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.author
     *
     * @return the value of t_article.author
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.author
     *
     * @param author the value for t_article.author
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.status
     *
     * @return the value of t_article.status
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.status
     *
     * @param status the value for t_article.status
     *
     * @mbggenerated Wed Sep 07 23:38:59 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }
    
	public static enum ArticleStat implements IntEnum<ComStat> {
		normal("1", "正常"), invalid("0", "失效");

		private final String index;
		private final String name;
		private ArticleStat(String index, String name) {
			this.index = index;
			this.name = name;
		}

		public static String getName(String index) {
			for (ArticleStat e : ArticleStat.values()) {
				if (e.getIndex().equals(index)) {
					return e.name;
				}
			}
			return null;
		}

		public String getName() {
			return name;
		}

		public String getIndex() {
			// TODO Auto-generated method stub
			return index;
		}
	}

	public String getStatDescribe(){
		return ArticleStat.getName(this.status);
	}
	
	public static enum ArticleType implements IntEnum<ComType>{
		type01("01","文章"), type02("02", "百科");

		private final String index;
		private final String name;
		private ArticleType(String index, String name) {
			this.index = index;
			this.name = name;
		}

		public static String getName(String index) {
			for (ArticleType e : ArticleType.values()) {
				if (e.getIndex().equals(index)) {
					return e.name;
				}
			}
			return null;
		}

		public String getName() {
			return name;
		}

		public String getIndex() {
			// TODO Auto-generated method stub
			return index;
		}
	}
	
	public String getTypeDescribe(){
		return ArticleType.getName(this.type);
	}
}