package com.gmzj.entity;

import java.util.Date;

import com.gmzj.entity.Cemetery.ComType;

public class CemArticle {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cem_article.id
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cem_article.title
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cem_article.type
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cem_article.content
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cem_article.time
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cem_article.img_url
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	private String imgUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cem_article.num
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	private Integer num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cem_article.author
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	private String author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cem_article.status
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cem_article.id
	 * @return  the value of t_cem_article.id
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cem_article.id
	 * @param id  the value for t_cem_article.id
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cem_article.title
	 * @return  the value of t_cem_article.title
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cem_article.title
	 * @param title  the value for t_cem_article.title
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cem_article.type
	 * @return  the value of t_cem_article.type
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cem_article.type
	 * @param type  the value for t_cem_article.type
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cem_article.content
	 * @return  the value of t_cem_article.content
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cem_article.content
	 * @param content  the value for t_cem_article.content
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cem_article.time
	 * @return  the value of t_cem_article.time
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cem_article.time
	 * @param time  the value for t_cem_article.time
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cem_article.img_url
	 * @return  the value of t_cem_article.img_url
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	public String getImgUrl() {
		return imgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cem_article.img_url
	 * @param imgUrl  the value for t_cem_article.img_url
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cem_article.num
	 * @return  the value of t_cem_article.num
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cem_article.num
	 * @param num  the value for t_cem_article.num
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cem_article.author
	 * @return  the value of t_cem_article.author
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cem_article.author
	 * @param author  the value for t_cem_article.author
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cem_article.status
	 * @return  the value of t_cem_article.status
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cem_article.status
	 * @param status  the value for t_cem_article.status
	 * @mbggenerated  Thu Nov 10 10:13:33 CST 2016
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	public static enum CemArtType implements IntEnum<ComType>{
		mdzx("1","墓地咨询"), mdfs("2", "墓地风水"), mdzn("3", "墓地指南");

		private final String index;
		private final String name;
		private CemArtType(String index, String name) {
			this.index = index;
			this.name = name;
		}

		public static String getName(String index) {
			for (CemArtType e : CemArtType.values()) {
				if (e.getIndex().equals(index)) {
					return e.name;
				}
			}
			return null;
		}

		public String getName() {
			return name;
		}

		public String getIndex() {
			// TODO Auto-generated method stub
			return index;
		}
	}
	
	public String getTypeDescribe(){
		return CemArtType.getName(this.type);
	}
}