package com.gmzj.entity;

import java.util.ArrayList;
import java.util.List;

public class CemeteryExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_cemetery
	 * @mbggenerated  Wed Oct 26 22:19:56 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_cemetery
	 * @mbggenerated  Wed Oct 26 22:19:56 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_cemetery
	 * @mbggenerated  Wed Oct 26 22:19:56 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cemetery
	 * @mbggenerated  Wed Oct 26 22:19:56 CST 2016
	 */
	public CemeteryExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cemetery
	 * @mbggenerated  Wed Oct 26 22:19:56 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cemetery
	 * @mbggenerated  Wed Oct 26 22:19:56 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cemetery
	 * @mbggenerated  Wed Oct 26 22:19:56 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cemetery
	 * @mbggenerated  Wed Oct 26 22:19:56 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cemetery
	 * @mbggenerated  Wed Oct 26 22:19:56 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cemetery
	 * @mbggenerated  Wed Oct 26 22:19:56 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cemetery
	 * @mbggenerated  Wed Oct 26 22:19:56 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cemetery
	 * @mbggenerated  Wed Oct 26 22:19:56 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cemetery
	 * @mbggenerated  Wed Oct 26 22:19:56 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cemetery
	 * @mbggenerated  Wed Oct 26 22:19:56 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_cemetery
	 * @mbggenerated  Wed Oct 26 22:19:56 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(String value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(String value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(String value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(String value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(String value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(String value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLike(String value) {
			addCriterion("type like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotLike(String value) {
			addCriterion("type not like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<String> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<String> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(String value1, String value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(String value1, String value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andScoreIsNull() {
			addCriterion("score is null");
			return (Criteria) this;
		}

		public Criteria andScoreIsNotNull() {
			addCriterion("score is not null");
			return (Criteria) this;
		}

		public Criteria andScoreEqualTo(String value) {
			addCriterion("score =", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotEqualTo(String value) {
			addCriterion("score <>", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThan(String value) {
			addCriterion("score >", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThanOrEqualTo(String value) {
			addCriterion("score >=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThan(String value) {
			addCriterion("score <", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThanOrEqualTo(String value) {
			addCriterion("score <=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLike(String value) {
			addCriterion("score like", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotLike(String value) {
			addCriterion("score not like", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreIn(List<String> values) {
			addCriterion("score in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotIn(List<String> values) {
			addCriterion("score not in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreBetween(String value1, String value2) {
			addCriterion("score between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotBetween(String value1, String value2) {
			addCriterion("score not between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andScoreFsIsNull() {
			addCriterion("score_fs is null");
			return (Criteria) this;
		}

		public Criteria andScoreFsIsNotNull() {
			addCriterion("score_fs is not null");
			return (Criteria) this;
		}

		public Criteria andScoreFsEqualTo(String value) {
			addCriterion("score_fs =", value, "scoreFs");
			return (Criteria) this;
		}

		public Criteria andScoreFsNotEqualTo(String value) {
			addCriterion("score_fs <>", value, "scoreFs");
			return (Criteria) this;
		}

		public Criteria andScoreFsGreaterThan(String value) {
			addCriterion("score_fs >", value, "scoreFs");
			return (Criteria) this;
		}

		public Criteria andScoreFsGreaterThanOrEqualTo(String value) {
			addCriterion("score_fs >=", value, "scoreFs");
			return (Criteria) this;
		}

		public Criteria andScoreFsLessThan(String value) {
			addCriterion("score_fs <", value, "scoreFs");
			return (Criteria) this;
		}

		public Criteria andScoreFsLessThanOrEqualTo(String value) {
			addCriterion("score_fs <=", value, "scoreFs");
			return (Criteria) this;
		}

		public Criteria andScoreFsLike(String value) {
			addCriterion("score_fs like", value, "scoreFs");
			return (Criteria) this;
		}

		public Criteria andScoreFsNotLike(String value) {
			addCriterion("score_fs not like", value, "scoreFs");
			return (Criteria) this;
		}

		public Criteria andScoreFsIn(List<String> values) {
			addCriterion("score_fs in", values, "scoreFs");
			return (Criteria) this;
		}

		public Criteria andScoreFsNotIn(List<String> values) {
			addCriterion("score_fs not in", values, "scoreFs");
			return (Criteria) this;
		}

		public Criteria andScoreFsBetween(String value1, String value2) {
			addCriterion("score_fs between", value1, value2, "scoreFs");
			return (Criteria) this;
		}

		public Criteria andScoreFsNotBetween(String value1, String value2) {
			addCriterion("score_fs not between", value1, value2, "scoreFs");
			return (Criteria) this;
		}

		public Criteria andScoreJtIsNull() {
			addCriterion("score_jt is null");
			return (Criteria) this;
		}

		public Criteria andScoreJtIsNotNull() {
			addCriterion("score_jt is not null");
			return (Criteria) this;
		}

		public Criteria andScoreJtEqualTo(String value) {
			addCriterion("score_jt =", value, "scoreJt");
			return (Criteria) this;
		}

		public Criteria andScoreJtNotEqualTo(String value) {
			addCriterion("score_jt <>", value, "scoreJt");
			return (Criteria) this;
		}

		public Criteria andScoreJtGreaterThan(String value) {
			addCriterion("score_jt >", value, "scoreJt");
			return (Criteria) this;
		}

		public Criteria andScoreJtGreaterThanOrEqualTo(String value) {
			addCriterion("score_jt >=", value, "scoreJt");
			return (Criteria) this;
		}

		public Criteria andScoreJtLessThan(String value) {
			addCriterion("score_jt <", value, "scoreJt");
			return (Criteria) this;
		}

		public Criteria andScoreJtLessThanOrEqualTo(String value) {
			addCriterion("score_jt <=", value, "scoreJt");
			return (Criteria) this;
		}

		public Criteria andScoreJtLike(String value) {
			addCriterion("score_jt like", value, "scoreJt");
			return (Criteria) this;
		}

		public Criteria andScoreJtNotLike(String value) {
			addCriterion("score_jt not like", value, "scoreJt");
			return (Criteria) this;
		}

		public Criteria andScoreJtIn(List<String> values) {
			addCriterion("score_jt in", values, "scoreJt");
			return (Criteria) this;
		}

		public Criteria andScoreJtNotIn(List<String> values) {
			addCriterion("score_jt not in", values, "scoreJt");
			return (Criteria) this;
		}

		public Criteria andScoreJtBetween(String value1, String value2) {
			addCriterion("score_jt between", value1, value2, "scoreJt");
			return (Criteria) this;
		}

		public Criteria andScoreJtNotBetween(String value1, String value2) {
			addCriterion("score_jt not between", value1, value2, "scoreJt");
			return (Criteria) this;
		}

		public Criteria andScoreHjIsNull() {
			addCriterion("score_hj is null");
			return (Criteria) this;
		}

		public Criteria andScoreHjIsNotNull() {
			addCriterion("score_hj is not null");
			return (Criteria) this;
		}

		public Criteria andScoreHjEqualTo(String value) {
			addCriterion("score_hj =", value, "scoreHj");
			return (Criteria) this;
		}

		public Criteria andScoreHjNotEqualTo(String value) {
			addCriterion("score_hj <>", value, "scoreHj");
			return (Criteria) this;
		}

		public Criteria andScoreHjGreaterThan(String value) {
			addCriterion("score_hj >", value, "scoreHj");
			return (Criteria) this;
		}

		public Criteria andScoreHjGreaterThanOrEqualTo(String value) {
			addCriterion("score_hj >=", value, "scoreHj");
			return (Criteria) this;
		}

		public Criteria andScoreHjLessThan(String value) {
			addCriterion("score_hj <", value, "scoreHj");
			return (Criteria) this;
		}

		public Criteria andScoreHjLessThanOrEqualTo(String value) {
			addCriterion("score_hj <=", value, "scoreHj");
			return (Criteria) this;
		}

		public Criteria andScoreHjLike(String value) {
			addCriterion("score_hj like", value, "scoreHj");
			return (Criteria) this;
		}

		public Criteria andScoreHjNotLike(String value) {
			addCriterion("score_hj not like", value, "scoreHj");
			return (Criteria) this;
		}

		public Criteria andScoreHjIn(List<String> values) {
			addCriterion("score_hj in", values, "scoreHj");
			return (Criteria) this;
		}

		public Criteria andScoreHjNotIn(List<String> values) {
			addCriterion("score_hj not in", values, "scoreHj");
			return (Criteria) this;
		}

		public Criteria andScoreHjBetween(String value1, String value2) {
			addCriterion("score_hj between", value1, value2, "scoreHj");
			return (Criteria) this;
		}

		public Criteria andScoreHjNotBetween(String value1, String value2) {
			addCriterion("score_hj not between", value1, value2, "scoreHj");
			return (Criteria) this;
		}

		public Criteria andScoreFwIsNull() {
			addCriterion("score_fw is null");
			return (Criteria) this;
		}

		public Criteria andScoreFwIsNotNull() {
			addCriterion("score_fw is not null");
			return (Criteria) this;
		}

		public Criteria andScoreFwEqualTo(String value) {
			addCriterion("score_fw =", value, "scoreFw");
			return (Criteria) this;
		}

		public Criteria andScoreFwNotEqualTo(String value) {
			addCriterion("score_fw <>", value, "scoreFw");
			return (Criteria) this;
		}

		public Criteria andScoreFwGreaterThan(String value) {
			addCriterion("score_fw >", value, "scoreFw");
			return (Criteria) this;
		}

		public Criteria andScoreFwGreaterThanOrEqualTo(String value) {
			addCriterion("score_fw >=", value, "scoreFw");
			return (Criteria) this;
		}

		public Criteria andScoreFwLessThan(String value) {
			addCriterion("score_fw <", value, "scoreFw");
			return (Criteria) this;
		}

		public Criteria andScoreFwLessThanOrEqualTo(String value) {
			addCriterion("score_fw <=", value, "scoreFw");
			return (Criteria) this;
		}

		public Criteria andScoreFwLike(String value) {
			addCriterion("score_fw like", value, "scoreFw");
			return (Criteria) this;
		}

		public Criteria andScoreFwNotLike(String value) {
			addCriterion("score_fw not like", value, "scoreFw");
			return (Criteria) this;
		}

		public Criteria andScoreFwIn(List<String> values) {
			addCriterion("score_fw in", values, "scoreFw");
			return (Criteria) this;
		}

		public Criteria andScoreFwNotIn(List<String> values) {
			addCriterion("score_fw not in", values, "scoreFw");
			return (Criteria) this;
		}

		public Criteria andScoreFwBetween(String value1, String value2) {
			addCriterion("score_fw between", value1, value2, "scoreFw");
			return (Criteria) this;
		}

		public Criteria andScoreFwNotBetween(String value1, String value2) {
			addCriterion("score_fw not between", value1, value2, "scoreFw");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(Long value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(Long value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(Long value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Long value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(Long value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(Long value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<Long> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<Long> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(Long value1, Long value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(Long value1, Long value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andSloganIsNull() {
			addCriterion("slogan is null");
			return (Criteria) this;
		}

		public Criteria andSloganIsNotNull() {
			addCriterion("slogan is not null");
			return (Criteria) this;
		}

		public Criteria andSloganEqualTo(String value) {
			addCriterion("slogan =", value, "slogan");
			return (Criteria) this;
		}

		public Criteria andSloganNotEqualTo(String value) {
			addCriterion("slogan <>", value, "slogan");
			return (Criteria) this;
		}

		public Criteria andSloganGreaterThan(String value) {
			addCriterion("slogan >", value, "slogan");
			return (Criteria) this;
		}

		public Criteria andSloganGreaterThanOrEqualTo(String value) {
			addCriterion("slogan >=", value, "slogan");
			return (Criteria) this;
		}

		public Criteria andSloganLessThan(String value) {
			addCriterion("slogan <", value, "slogan");
			return (Criteria) this;
		}

		public Criteria andSloganLessThanOrEqualTo(String value) {
			addCriterion("slogan <=", value, "slogan");
			return (Criteria) this;
		}

		public Criteria andSloganLike(String value) {
			addCriterion("slogan like", value, "slogan");
			return (Criteria) this;
		}

		public Criteria andSloganNotLike(String value) {
			addCriterion("slogan not like", value, "slogan");
			return (Criteria) this;
		}

		public Criteria andSloganIn(List<String> values) {
			addCriterion("slogan in", values, "slogan");
			return (Criteria) this;
		}

		public Criteria andSloganNotIn(List<String> values) {
			addCriterion("slogan not in", values, "slogan");
			return (Criteria) this;
		}

		public Criteria andSloganBetween(String value1, String value2) {
			addCriterion("slogan between", value1, value2, "slogan");
			return (Criteria) this;
		}

		public Criteria andSloganNotBetween(String value1, String value2) {
			addCriterion("slogan not between", value1, value2, "slogan");
			return (Criteria) this;
		}

		public Criteria andScaleIsNull() {
			addCriterion("scale is null");
			return (Criteria) this;
		}

		public Criteria andScaleIsNotNull() {
			addCriterion("scale is not null");
			return (Criteria) this;
		}

		public Criteria andScaleEqualTo(Integer value) {
			addCriterion("scale =", value, "scale");
			return (Criteria) this;
		}

		public Criteria andScaleNotEqualTo(Integer value) {
			addCriterion("scale <>", value, "scale");
			return (Criteria) this;
		}

		public Criteria andScaleGreaterThan(Integer value) {
			addCriterion("scale >", value, "scale");
			return (Criteria) this;
		}

		public Criteria andScaleGreaterThanOrEqualTo(Integer value) {
			addCriterion("scale >=", value, "scale");
			return (Criteria) this;
		}

		public Criteria andScaleLessThan(Integer value) {
			addCriterion("scale <", value, "scale");
			return (Criteria) this;
		}

		public Criteria andScaleLessThanOrEqualTo(Integer value) {
			addCriterion("scale <=", value, "scale");
			return (Criteria) this;
		}

		public Criteria andScaleIn(List<Integer> values) {
			addCriterion("scale in", values, "scale");
			return (Criteria) this;
		}

		public Criteria andScaleNotIn(List<Integer> values) {
			addCriterion("scale not in", values, "scale");
			return (Criteria) this;
		}

		public Criteria andScaleBetween(Integer value1, Integer value2) {
			addCriterion("scale between", value1, value2, "scale");
			return (Criteria) this;
		}

		public Criteria andScaleNotBetween(Integer value1, Integer value2) {
			addCriterion("scale not between", value1, value2, "scale");
			return (Criteria) this;
		}

		public Criteria andRegionnoIsNull() {
			addCriterion("regionno is null");
			return (Criteria) this;
		}

		public Criteria andRegionnoIsNotNull() {
			addCriterion("regionno is not null");
			return (Criteria) this;
		}

		public Criteria andRegionnoEqualTo(String value) {
			addCriterion("regionno =", value, "regionno");
			return (Criteria) this;
		}

		public Criteria andRegionnoNotEqualTo(String value) {
			addCriterion("regionno <>", value, "regionno");
			return (Criteria) this;
		}

		public Criteria andRegionnoGreaterThan(String value) {
			addCriterion("regionno >", value, "regionno");
			return (Criteria) this;
		}

		public Criteria andRegionnoGreaterThanOrEqualTo(String value) {
			addCriterion("regionno >=", value, "regionno");
			return (Criteria) this;
		}

		public Criteria andRegionnoLessThan(String value) {
			addCriterion("regionno <", value, "regionno");
			return (Criteria) this;
		}

		public Criteria andRegionnoLessThanOrEqualTo(String value) {
			addCriterion("regionno <=", value, "regionno");
			return (Criteria) this;
		}

		public Criteria andRegionnoLike(String value) {
			addCriterion("regionno like", value, "regionno");
			return (Criteria) this;
		}

		public Criteria andRegionnoNotLike(String value) {
			addCriterion("regionno not like", value, "regionno");
			return (Criteria) this;
		}

		public Criteria andRegionnoIn(List<String> values) {
			addCriterion("regionno in", values, "regionno");
			return (Criteria) this;
		}

		public Criteria andRegionnoNotIn(List<String> values) {
			addCriterion("regionno not in", values, "regionno");
			return (Criteria) this;
		}

		public Criteria andRegionnoBetween(String value1, String value2) {
			addCriterion("regionno between", value1, value2, "regionno");
			return (Criteria) this;
		}

		public Criteria andRegionnoNotBetween(String value1, String value2) {
			addCriterion("regionno not between", value1, value2, "regionno");
			return (Criteria) this;
		}

		public Criteria andDistanceIsNull() {
			addCriterion("distance is null");
			return (Criteria) this;
		}

		public Criteria andDistanceIsNotNull() {
			addCriterion("distance is not null");
			return (Criteria) this;
		}

		public Criteria andDistanceEqualTo(Integer value) {
			addCriterion("distance =", value, "distance");
			return (Criteria) this;
		}

		public Criteria andDistanceNotEqualTo(Integer value) {
			addCriterion("distance <>", value, "distance");
			return (Criteria) this;
		}

		public Criteria andDistanceGreaterThan(Integer value) {
			addCriterion("distance >", value, "distance");
			return (Criteria) this;
		}

		public Criteria andDistanceGreaterThanOrEqualTo(Integer value) {
			addCriterion("distance >=", value, "distance");
			return (Criteria) this;
		}

		public Criteria andDistanceLessThan(Integer value) {
			addCriterion("distance <", value, "distance");
			return (Criteria) this;
		}

		public Criteria andDistanceLessThanOrEqualTo(Integer value) {
			addCriterion("distance <=", value, "distance");
			return (Criteria) this;
		}

		public Criteria andDistanceIn(List<Integer> values) {
			addCriterion("distance in", values, "distance");
			return (Criteria) this;
		}

		public Criteria andDistanceNotIn(List<Integer> values) {
			addCriterion("distance not in", values, "distance");
			return (Criteria) this;
		}

		public Criteria andDistanceBetween(Integer value1, Integer value2) {
			addCriterion("distance between", value1, value2, "distance");
			return (Criteria) this;
		}

		public Criteria andDistanceNotBetween(Integer value1, Integer value2) {
			addCriterion("distance not between", value1, value2, "distance");
			return (Criteria) this;
		}

		public Criteria andBespeakIsNull() {
			addCriterion("bespeak is null");
			return (Criteria) this;
		}

		public Criteria andBespeakIsNotNull() {
			addCriterion("bespeak is not null");
			return (Criteria) this;
		}

		public Criteria andBespeakEqualTo(Integer value) {
			addCriterion("bespeak =", value, "bespeak");
			return (Criteria) this;
		}

		public Criteria andBespeakNotEqualTo(Integer value) {
			addCriterion("bespeak <>", value, "bespeak");
			return (Criteria) this;
		}

		public Criteria andBespeakGreaterThan(Integer value) {
			addCriterion("bespeak >", value, "bespeak");
			return (Criteria) this;
		}

		public Criteria andBespeakGreaterThanOrEqualTo(Integer value) {
			addCriterion("bespeak >=", value, "bespeak");
			return (Criteria) this;
		}

		public Criteria andBespeakLessThan(Integer value) {
			addCriterion("bespeak <", value, "bespeak");
			return (Criteria) this;
		}

		public Criteria andBespeakLessThanOrEqualTo(Integer value) {
			addCriterion("bespeak <=", value, "bespeak");
			return (Criteria) this;
		}

		public Criteria andBespeakIn(List<Integer> values) {
			addCriterion("bespeak in", values, "bespeak");
			return (Criteria) this;
		}

		public Criteria andBespeakNotIn(List<Integer> values) {
			addCriterion("bespeak not in", values, "bespeak");
			return (Criteria) this;
		}

		public Criteria andBespeakBetween(Integer value1, Integer value2) {
			addCriterion("bespeak between", value1, value2, "bespeak");
			return (Criteria) this;
		}

		public Criteria andBespeakNotBetween(Integer value1, Integer value2) {
			addCriterion("bespeak not between", value1, value2, "bespeak");
			return (Criteria) this;
		}

		public Criteria andViewNumIsNull() {
			addCriterion("view_num is null");
			return (Criteria) this;
		}

		public Criteria andViewNumIsNotNull() {
			addCriterion("view_num is not null");
			return (Criteria) this;
		}

		public Criteria andViewNumEqualTo(Integer value) {
			addCriterion("view_num =", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumNotEqualTo(Integer value) {
			addCriterion("view_num <>", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumGreaterThan(Integer value) {
			addCriterion("view_num >", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("view_num >=", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumLessThan(Integer value) {
			addCriterion("view_num <", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumLessThanOrEqualTo(Integer value) {
			addCriterion("view_num <=", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumIn(List<Integer> values) {
			addCriterion("view_num in", values, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumNotIn(List<Integer> values) {
			addCriterion("view_num not in", values, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumBetween(Integer value1, Integer value2) {
			addCriterion("view_num between", value1, value2, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumNotBetween(Integer value1, Integer value2) {
			addCriterion("view_num not between", value1, value2, "viewNum");
			return (Criteria) this;
		}

		public Criteria andApprovalDepIsNull() {
			addCriterion("approval_dep is null");
			return (Criteria) this;
		}

		public Criteria andApprovalDepIsNotNull() {
			addCriterion("approval_dep is not null");
			return (Criteria) this;
		}

		public Criteria andApprovalDepEqualTo(String value) {
			addCriterion("approval_dep =", value, "approvalDep");
			return (Criteria) this;
		}

		public Criteria andApprovalDepNotEqualTo(String value) {
			addCriterion("approval_dep <>", value, "approvalDep");
			return (Criteria) this;
		}

		public Criteria andApprovalDepGreaterThan(String value) {
			addCriterion("approval_dep >", value, "approvalDep");
			return (Criteria) this;
		}

		public Criteria andApprovalDepGreaterThanOrEqualTo(String value) {
			addCriterion("approval_dep >=", value, "approvalDep");
			return (Criteria) this;
		}

		public Criteria andApprovalDepLessThan(String value) {
			addCriterion("approval_dep <", value, "approvalDep");
			return (Criteria) this;
		}

		public Criteria andApprovalDepLessThanOrEqualTo(String value) {
			addCriterion("approval_dep <=", value, "approvalDep");
			return (Criteria) this;
		}

		public Criteria andApprovalDepLike(String value) {
			addCriterion("approval_dep like", value, "approvalDep");
			return (Criteria) this;
		}

		public Criteria andApprovalDepNotLike(String value) {
			addCriterion("approval_dep not like", value, "approvalDep");
			return (Criteria) this;
		}

		public Criteria andApprovalDepIn(List<String> values) {
			addCriterion("approval_dep in", values, "approvalDep");
			return (Criteria) this;
		}

		public Criteria andApprovalDepNotIn(List<String> values) {
			addCriterion("approval_dep not in", values, "approvalDep");
			return (Criteria) this;
		}

		public Criteria andApprovalDepBetween(String value1, String value2) {
			addCriterion("approval_dep between", value1, value2, "approvalDep");
			return (Criteria) this;
		}

		public Criteria andApprovalDepNotBetween(String value1, String value2) {
			addCriterion("approval_dep not between", value1, value2,
					"approvalDep");
			return (Criteria) this;
		}

		public Criteria andCharacteristicIsNull() {
			addCriterion("characteristic is null");
			return (Criteria) this;
		}

		public Criteria andCharacteristicIsNotNull() {
			addCriterion("characteristic is not null");
			return (Criteria) this;
		}

		public Criteria andCharacteristicEqualTo(String value) {
			addCriterion("characteristic =", value, "characteristic");
			return (Criteria) this;
		}

		public Criteria andCharacteristicNotEqualTo(String value) {
			addCriterion("characteristic <>", value, "characteristic");
			return (Criteria) this;
		}

		public Criteria andCharacteristicGreaterThan(String value) {
			addCriterion("characteristic >", value, "characteristic");
			return (Criteria) this;
		}

		public Criteria andCharacteristicGreaterThanOrEqualTo(String value) {
			addCriterion("characteristic >=", value, "characteristic");
			return (Criteria) this;
		}

		public Criteria andCharacteristicLessThan(String value) {
			addCriterion("characteristic <", value, "characteristic");
			return (Criteria) this;
		}

		public Criteria andCharacteristicLessThanOrEqualTo(String value) {
			addCriterion("characteristic <=", value, "characteristic");
			return (Criteria) this;
		}

		public Criteria andCharacteristicLike(String value) {
			addCriterion("characteristic like", value, "characteristic");
			return (Criteria) this;
		}

		public Criteria andCharacteristicNotLike(String value) {
			addCriterion("characteristic not like", value, "characteristic");
			return (Criteria) this;
		}

		public Criteria andCharacteristicIn(List<String> values) {
			addCriterion("characteristic in", values, "characteristic");
			return (Criteria) this;
		}

		public Criteria andCharacteristicNotIn(List<String> values) {
			addCriterion("characteristic not in", values, "characteristic");
			return (Criteria) this;
		}

		public Criteria andCharacteristicBetween(String value1, String value2) {
			addCriterion("characteristic between", value1, value2,
					"characteristic");
			return (Criteria) this;
		}

		public Criteria andCharacteristicNotBetween(String value1, String value2) {
			addCriterion("characteristic not between", value1, value2,
					"characteristic");
			return (Criteria) this;
		}

		public Criteria andPreferentialIsNull() {
			addCriterion("preferential is null");
			return (Criteria) this;
		}

		public Criteria andPreferentialIsNotNull() {
			addCriterion("preferential is not null");
			return (Criteria) this;
		}

		public Criteria andPreferentialEqualTo(String value) {
			addCriterion("preferential =", value, "preferential");
			return (Criteria) this;
		}

		public Criteria andPreferentialNotEqualTo(String value) {
			addCriterion("preferential <>", value, "preferential");
			return (Criteria) this;
		}

		public Criteria andPreferentialGreaterThan(String value) {
			addCriterion("preferential >", value, "preferential");
			return (Criteria) this;
		}

		public Criteria andPreferentialGreaterThanOrEqualTo(String value) {
			addCriterion("preferential >=", value, "preferential");
			return (Criteria) this;
		}

		public Criteria andPreferentialLessThan(String value) {
			addCriterion("preferential <", value, "preferential");
			return (Criteria) this;
		}

		public Criteria andPreferentialLessThanOrEqualTo(String value) {
			addCriterion("preferential <=", value, "preferential");
			return (Criteria) this;
		}

		public Criteria andPreferentialLike(String value) {
			addCriterion("preferential like", value, "preferential");
			return (Criteria) this;
		}

		public Criteria andPreferentialNotLike(String value) {
			addCriterion("preferential not like", value, "preferential");
			return (Criteria) this;
		}

		public Criteria andPreferentialIn(List<String> values) {
			addCriterion("preferential in", values, "preferential");
			return (Criteria) this;
		}

		public Criteria andPreferentialNotIn(List<String> values) {
			addCriterion("preferential not in", values, "preferential");
			return (Criteria) this;
		}

		public Criteria andPreferentialBetween(String value1, String value2) {
			addCriterion("preferential between", value1, value2, "preferential");
			return (Criteria) this;
		}

		public Criteria andPreferentialNotBetween(String value1, String value2) {
			addCriterion("preferential not between", value1, value2,
					"preferential");
			return (Criteria) this;
		}

		public Criteria andAuthenticationIsNull() {
			addCriterion("authentication is null");
			return (Criteria) this;
		}

		public Criteria andAuthenticationIsNotNull() {
			addCriterion("authentication is not null");
			return (Criteria) this;
		}

		public Criteria andAuthenticationEqualTo(Boolean value) {
			addCriterion("authentication =", value, "authentication");
			return (Criteria) this;
		}

		public Criteria andAuthenticationNotEqualTo(Boolean value) {
			addCriterion("authentication <>", value, "authentication");
			return (Criteria) this;
		}

		public Criteria andAuthenticationGreaterThan(Boolean value) {
			addCriterion("authentication >", value, "authentication");
			return (Criteria) this;
		}

		public Criteria andAuthenticationGreaterThanOrEqualTo(Boolean value) {
			addCriterion("authentication >=", value, "authentication");
			return (Criteria) this;
		}

		public Criteria andAuthenticationLessThan(Boolean value) {
			addCriterion("authentication <", value, "authentication");
			return (Criteria) this;
		}

		public Criteria andAuthenticationLessThanOrEqualTo(Boolean value) {
			addCriterion("authentication <=", value, "authentication");
			return (Criteria) this;
		}

		public Criteria andAuthenticationIn(List<Boolean> values) {
			addCriterion("authentication in", values, "authentication");
			return (Criteria) this;
		}

		public Criteria andAuthenticationNotIn(List<Boolean> values) {
			addCriterion("authentication not in", values, "authentication");
			return (Criteria) this;
		}

		public Criteria andAuthenticationBetween(Boolean value1, Boolean value2) {
			addCriterion("authentication between", value1, value2,
					"authentication");
			return (Criteria) this;
		}

		public Criteria andAuthenticationNotBetween(Boolean value1,
				Boolean value2) {
			addCriterion("authentication not between", value1, value2,
					"authentication");
			return (Criteria) this;
		}

		public Criteria andDiscountIsNull() {
			addCriterion("discount is null");
			return (Criteria) this;
		}

		public Criteria andDiscountIsNotNull() {
			addCriterion("discount is not null");
			return (Criteria) this;
		}

		public Criteria andDiscountEqualTo(Boolean value) {
			addCriterion("discount =", value, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountNotEqualTo(Boolean value) {
			addCriterion("discount <>", value, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountGreaterThan(Boolean value) {
			addCriterion("discount >", value, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountGreaterThanOrEqualTo(Boolean value) {
			addCriterion("discount >=", value, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountLessThan(Boolean value) {
			addCriterion("discount <", value, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountLessThanOrEqualTo(Boolean value) {
			addCriterion("discount <=", value, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountIn(List<Boolean> values) {
			addCriterion("discount in", values, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountNotIn(List<Boolean> values) {
			addCriterion("discount not in", values, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountBetween(Boolean value1, Boolean value2) {
			addCriterion("discount between", value1, value2, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountNotBetween(Boolean value1, Boolean value2) {
			addCriterion("discount not between", value1, value2, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountNumIsNull() {
			addCriterion("discount_num is null");
			return (Criteria) this;
		}

		public Criteria andDiscountNumIsNotNull() {
			addCriterion("discount_num is not null");
			return (Criteria) this;
		}

		public Criteria andDiscountNumEqualTo(Integer value) {
			addCriterion("discount_num =", value, "discountNum");
			return (Criteria) this;
		}

		public Criteria andDiscountNumNotEqualTo(Integer value) {
			addCriterion("discount_num <>", value, "discountNum");
			return (Criteria) this;
		}

		public Criteria andDiscountNumGreaterThan(Integer value) {
			addCriterion("discount_num >", value, "discountNum");
			return (Criteria) this;
		}

		public Criteria andDiscountNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("discount_num >=", value, "discountNum");
			return (Criteria) this;
		}

		public Criteria andDiscountNumLessThan(Integer value) {
			addCriterion("discount_num <", value, "discountNum");
			return (Criteria) this;
		}

		public Criteria andDiscountNumLessThanOrEqualTo(Integer value) {
			addCriterion("discount_num <=", value, "discountNum");
			return (Criteria) this;
		}

		public Criteria andDiscountNumIn(List<Integer> values) {
			addCriterion("discount_num in", values, "discountNum");
			return (Criteria) this;
		}

		public Criteria andDiscountNumNotIn(List<Integer> values) {
			addCriterion("discount_num not in", values, "discountNum");
			return (Criteria) this;
		}

		public Criteria andDiscountNumBetween(Integer value1, Integer value2) {
			addCriterion("discount_num between", value1, value2, "discountNum");
			return (Criteria) this;
		}

		public Criteria andDiscountNumNotBetween(Integer value1, Integer value2) {
			addCriterion("discount_num not between", value1, value2,
					"discountNum");
			return (Criteria) this;
		}

		public Criteria andImgUrlIsNull() {
			addCriterion("img_url is null");
			return (Criteria) this;
		}

		public Criteria andImgUrlIsNotNull() {
			addCriterion("img_url is not null");
			return (Criteria) this;
		}

		public Criteria andImgUrlEqualTo(String value) {
			addCriterion("img_url =", value, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlNotEqualTo(String value) {
			addCriterion("img_url <>", value, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlGreaterThan(String value) {
			addCriterion("img_url >", value, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlGreaterThanOrEqualTo(String value) {
			addCriterion("img_url >=", value, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlLessThan(String value) {
			addCriterion("img_url <", value, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlLessThanOrEqualTo(String value) {
			addCriterion("img_url <=", value, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlLike(String value) {
			addCriterion("img_url like", value, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlNotLike(String value) {
			addCriterion("img_url not like", value, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlIn(List<String> values) {
			addCriterion("img_url in", values, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlNotIn(List<String> values) {
			addCriterion("img_url not in", values, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlBetween(String value1, String value2) {
			addCriterion("img_url between", value1, value2, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlNotBetween(String value1, String value2) {
			addCriterion("img_url not between", value1, value2, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andIntroduceIsNull() {
			addCriterion("introduce is null");
			return (Criteria) this;
		}

		public Criteria andIntroduceIsNotNull() {
			addCriterion("introduce is not null");
			return (Criteria) this;
		}

		public Criteria andIntroduceEqualTo(String value) {
			addCriterion("introduce =", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceNotEqualTo(String value) {
			addCriterion("introduce <>", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceGreaterThan(String value) {
			addCriterion("introduce >", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceGreaterThanOrEqualTo(String value) {
			addCriterion("introduce >=", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceLessThan(String value) {
			addCriterion("introduce <", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceLessThanOrEqualTo(String value) {
			addCriterion("introduce <=", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceLike(String value) {
			addCriterion("introduce like", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceNotLike(String value) {
			addCriterion("introduce not like", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceIn(List<String> values) {
			addCriterion("introduce in", values, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceNotIn(List<String> values) {
			addCriterion("introduce not in", values, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceBetween(String value1, String value2) {
			addCriterion("introduce between", value1, value2, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceNotBetween(String value1, String value2) {
			addCriterion("introduce not between", value1, value2, "introduce");
			return (Criteria) this;
		}

		public Criteria andHotlineIsNull() {
			addCriterion("hotline is null");
			return (Criteria) this;
		}

		public Criteria andHotlineIsNotNull() {
			addCriterion("hotline is not null");
			return (Criteria) this;
		}

		public Criteria andHotlineEqualTo(String value) {
			addCriterion("hotline =", value, "hotline");
			return (Criteria) this;
		}

		public Criteria andHotlineNotEqualTo(String value) {
			addCriterion("hotline <>", value, "hotline");
			return (Criteria) this;
		}

		public Criteria andHotlineGreaterThan(String value) {
			addCriterion("hotline >", value, "hotline");
			return (Criteria) this;
		}

		public Criteria andHotlineGreaterThanOrEqualTo(String value) {
			addCriterion("hotline >=", value, "hotline");
			return (Criteria) this;
		}

		public Criteria andHotlineLessThan(String value) {
			addCriterion("hotline <", value, "hotline");
			return (Criteria) this;
		}

		public Criteria andHotlineLessThanOrEqualTo(String value) {
			addCriterion("hotline <=", value, "hotline");
			return (Criteria) this;
		}

		public Criteria andHotlineLike(String value) {
			addCriterion("hotline like", value, "hotline");
			return (Criteria) this;
		}

		public Criteria andHotlineNotLike(String value) {
			addCriterion("hotline not like", value, "hotline");
			return (Criteria) this;
		}

		public Criteria andHotlineIn(List<String> values) {
			addCriterion("hotline in", values, "hotline");
			return (Criteria) this;
		}

		public Criteria andHotlineNotIn(List<String> values) {
			addCriterion("hotline not in", values, "hotline");
			return (Criteria) this;
		}

		public Criteria andHotlineBetween(String value1, String value2) {
			addCriterion("hotline between", value1, value2, "hotline");
			return (Criteria) this;
		}

		public Criteria andHotlineNotBetween(String value1, String value2) {
			addCriterion("hotline not between", value1, value2, "hotline");
			return (Criteria) this;
		}

		public Criteria andCarIsNull() {
			addCriterion("car is null");
			return (Criteria) this;
		}

		public Criteria andCarIsNotNull() {
			addCriterion("car is not null");
			return (Criteria) this;
		}

		public Criteria andCarEqualTo(String value) {
			addCriterion("car =", value, "car");
			return (Criteria) this;
		}

		public Criteria andCarNotEqualTo(String value) {
			addCriterion("car <>", value, "car");
			return (Criteria) this;
		}

		public Criteria andCarGreaterThan(String value) {
			addCriterion("car >", value, "car");
			return (Criteria) this;
		}

		public Criteria andCarGreaterThanOrEqualTo(String value) {
			addCriterion("car >=", value, "car");
			return (Criteria) this;
		}

		public Criteria andCarLessThan(String value) {
			addCriterion("car <", value, "car");
			return (Criteria) this;
		}

		public Criteria andCarLessThanOrEqualTo(String value) {
			addCriterion("car <=", value, "car");
			return (Criteria) this;
		}

		public Criteria andCarLike(String value) {
			addCriterion("car like", value, "car");
			return (Criteria) this;
		}

		public Criteria andCarNotLike(String value) {
			addCriterion("car not like", value, "car");
			return (Criteria) this;
		}

		public Criteria andCarIn(List<String> values) {
			addCriterion("car in", values, "car");
			return (Criteria) this;
		}

		public Criteria andCarNotIn(List<String> values) {
			addCriterion("car not in", values, "car");
			return (Criteria) this;
		}

		public Criteria andCarBetween(String value1, String value2) {
			addCriterion("car between", value1, value2, "car");
			return (Criteria) this;
		}

		public Criteria andCarNotBetween(String value1, String value2) {
			addCriterion("car not between", value1, value2, "car");
			return (Criteria) this;
		}

		public Criteria andPolicyIsNull() {
			addCriterion("policy is null");
			return (Criteria) this;
		}

		public Criteria andPolicyIsNotNull() {
			addCriterion("policy is not null");
			return (Criteria) this;
		}

		public Criteria andPolicyEqualTo(String value) {
			addCriterion("policy =", value, "policy");
			return (Criteria) this;
		}

		public Criteria andPolicyNotEqualTo(String value) {
			addCriterion("policy <>", value, "policy");
			return (Criteria) this;
		}

		public Criteria andPolicyGreaterThan(String value) {
			addCriterion("policy >", value, "policy");
			return (Criteria) this;
		}

		public Criteria andPolicyGreaterThanOrEqualTo(String value) {
			addCriterion("policy >=", value, "policy");
			return (Criteria) this;
		}

		public Criteria andPolicyLessThan(String value) {
			addCriterion("policy <", value, "policy");
			return (Criteria) this;
		}

		public Criteria andPolicyLessThanOrEqualTo(String value) {
			addCriterion("policy <=", value, "policy");
			return (Criteria) this;
		}

		public Criteria andPolicyLike(String value) {
			addCriterion("policy like", value, "policy");
			return (Criteria) this;
		}

		public Criteria andPolicyNotLike(String value) {
			addCriterion("policy not like", value, "policy");
			return (Criteria) this;
		}

		public Criteria andPolicyIn(List<String> values) {
			addCriterion("policy in", values, "policy");
			return (Criteria) this;
		}

		public Criteria andPolicyNotIn(List<String> values) {
			addCriterion("policy not in", values, "policy");
			return (Criteria) this;
		}

		public Criteria andPolicyBetween(String value1, String value2) {
			addCriterion("policy between", value1, value2, "policy");
			return (Criteria) this;
		}

		public Criteria andPolicyNotBetween(String value1, String value2) {
			addCriterion("policy not between", value1, value2, "policy");
			return (Criteria) this;
		}

		public Criteria andTombNumIsNull() {
			addCriterion("tomb_num is null");
			return (Criteria) this;
		}

		public Criteria andTombNumIsNotNull() {
			addCriterion("tomb_num is not null");
			return (Criteria) this;
		}

		public Criteria andTombNumEqualTo(Integer value) {
			addCriterion("tomb_num =", value, "tombNum");
			return (Criteria) this;
		}

		public Criteria andTombNumNotEqualTo(Integer value) {
			addCriterion("tomb_num <>", value, "tombNum");
			return (Criteria) this;
		}

		public Criteria andTombNumGreaterThan(Integer value) {
			addCriterion("tomb_num >", value, "tombNum");
			return (Criteria) this;
		}

		public Criteria andTombNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("tomb_num >=", value, "tombNum");
			return (Criteria) this;
		}

		public Criteria andTombNumLessThan(Integer value) {
			addCriterion("tomb_num <", value, "tombNum");
			return (Criteria) this;
		}

		public Criteria andTombNumLessThanOrEqualTo(Integer value) {
			addCriterion("tomb_num <=", value, "tombNum");
			return (Criteria) this;
		}

		public Criteria andTombNumIn(List<Integer> values) {
			addCriterion("tomb_num in", values, "tombNum");
			return (Criteria) this;
		}

		public Criteria andTombNumNotIn(List<Integer> values) {
			addCriterion("tomb_num not in", values, "tombNum");
			return (Criteria) this;
		}

		public Criteria andTombNumBetween(Integer value1, Integer value2) {
			addCriterion("tomb_num between", value1, value2, "tombNum");
			return (Criteria) this;
		}

		public Criteria andTombNumNotBetween(Integer value1, Integer value2) {
			addCriterion("tomb_num not between", value1, value2, "tombNum");
			return (Criteria) this;
		}

		public Criteria andIsSpecialCarIsNull() {
			addCriterion("is_special_car is null");
			return (Criteria) this;
		}

		public Criteria andIsSpecialCarIsNotNull() {
			addCriterion("is_special_car is not null");
			return (Criteria) this;
		}

		public Criteria andIsSpecialCarEqualTo(Boolean value) {
			addCriterion("is_special_car =", value, "isSpecialCar");
			return (Criteria) this;
		}

		public Criteria andIsSpecialCarNotEqualTo(Boolean value) {
			addCriterion("is_special_car <>", value, "isSpecialCar");
			return (Criteria) this;
		}

		public Criteria andIsSpecialCarGreaterThan(Boolean value) {
			addCriterion("is_special_car >", value, "isSpecialCar");
			return (Criteria) this;
		}

		public Criteria andIsSpecialCarGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_special_car >=", value, "isSpecialCar");
			return (Criteria) this;
		}

		public Criteria andIsSpecialCarLessThan(Boolean value) {
			addCriterion("is_special_car <", value, "isSpecialCar");
			return (Criteria) this;
		}

		public Criteria andIsSpecialCarLessThanOrEqualTo(Boolean value) {
			addCriterion("is_special_car <=", value, "isSpecialCar");
			return (Criteria) this;
		}

		public Criteria andIsSpecialCarIn(List<Boolean> values) {
			addCriterion("is_special_car in", values, "isSpecialCar");
			return (Criteria) this;
		}

		public Criteria andIsSpecialCarNotIn(List<Boolean> values) {
			addCriterion("is_special_car not in", values, "isSpecialCar");
			return (Criteria) this;
		}

		public Criteria andIsSpecialCarBetween(Boolean value1, Boolean value2) {
			addCriterion("is_special_car between", value1, value2,
					"isSpecialCar");
			return (Criteria) this;
		}

		public Criteria andIsSpecialCarNotBetween(Boolean value1, Boolean value2) {
			addCriterion("is_special_car not between", value1, value2,
					"isSpecialCar");
			return (Criteria) this;
		}

		public Criteria andIsO2oIsNull() {
			addCriterion("is_o2o is null");
			return (Criteria) this;
		}

		public Criteria andIsO2oIsNotNull() {
			addCriterion("is_o2o is not null");
			return (Criteria) this;
		}

		public Criteria andIsO2oEqualTo(Boolean value) {
			addCriterion("is_o2o =", value, "isO2o");
			return (Criteria) this;
		}

		public Criteria andIsO2oNotEqualTo(Boolean value) {
			addCriterion("is_o2o <>", value, "isO2o");
			return (Criteria) this;
		}

		public Criteria andIsO2oGreaterThan(Boolean value) {
			addCriterion("is_o2o >", value, "isO2o");
			return (Criteria) this;
		}

		public Criteria andIsO2oGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_o2o >=", value, "isO2o");
			return (Criteria) this;
		}

		public Criteria andIsO2oLessThan(Boolean value) {
			addCriterion("is_o2o <", value, "isO2o");
			return (Criteria) this;
		}

		public Criteria andIsO2oLessThanOrEqualTo(Boolean value) {
			addCriterion("is_o2o <=", value, "isO2o");
			return (Criteria) this;
		}

		public Criteria andIsO2oIn(List<Boolean> values) {
			addCriterion("is_o2o in", values, "isO2o");
			return (Criteria) this;
		}

		public Criteria andIsO2oNotIn(List<Boolean> values) {
			addCriterion("is_o2o not in", values, "isO2o");
			return (Criteria) this;
		}

		public Criteria andIsO2oBetween(Boolean value1, Boolean value2) {
			addCriterion("is_o2o between", value1, value2, "isO2o");
			return (Criteria) this;
		}

		public Criteria andIsO2oNotBetween(Boolean value1, Boolean value2) {
			addCriterion("is_o2o not between", value1, value2, "isO2o");
			return (Criteria) this;
		}

		public Criteria andIsRetainAshesIsNull() {
			addCriterion("is_retain_ashes is null");
			return (Criteria) this;
		}

		public Criteria andIsRetainAshesIsNotNull() {
			addCriterion("is_retain_ashes is not null");
			return (Criteria) this;
		}

		public Criteria andIsRetainAshesEqualTo(Boolean value) {
			addCriterion("is_retain_ashes =", value, "isRetainAshes");
			return (Criteria) this;
		}

		public Criteria andIsRetainAshesNotEqualTo(Boolean value) {
			addCriterion("is_retain_ashes <>", value, "isRetainAshes");
			return (Criteria) this;
		}

		public Criteria andIsRetainAshesGreaterThan(Boolean value) {
			addCriterion("is_retain_ashes >", value, "isRetainAshes");
			return (Criteria) this;
		}

		public Criteria andIsRetainAshesGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_retain_ashes >=", value, "isRetainAshes");
			return (Criteria) this;
		}

		public Criteria andIsRetainAshesLessThan(Boolean value) {
			addCriterion("is_retain_ashes <", value, "isRetainAshes");
			return (Criteria) this;
		}

		public Criteria andIsRetainAshesLessThanOrEqualTo(Boolean value) {
			addCriterion("is_retain_ashes <=", value, "isRetainAshes");
			return (Criteria) this;
		}

		public Criteria andIsRetainAshesIn(List<Boolean> values) {
			addCriterion("is_retain_ashes in", values, "isRetainAshes");
			return (Criteria) this;
		}

		public Criteria andIsRetainAshesNotIn(List<Boolean> values) {
			addCriterion("is_retain_ashes not in", values, "isRetainAshes");
			return (Criteria) this;
		}

		public Criteria andIsRetainAshesBetween(Boolean value1, Boolean value2) {
			addCriterion("is_retain_ashes between", value1, value2,
					"isRetainAshes");
			return (Criteria) this;
		}

		public Criteria andIsRetainAshesNotBetween(Boolean value1,
				Boolean value2) {
			addCriterion("is_retain_ashes not between", value1, value2,
					"isRetainAshes");
			return (Criteria) this;
		}

		public Criteria andIsBuryIsNull() {
			addCriterion("is_bury is null");
			return (Criteria) this;
		}

		public Criteria andIsBuryIsNotNull() {
			addCriterion("is_bury is not null");
			return (Criteria) this;
		}

		public Criteria andIsBuryEqualTo(Boolean value) {
			addCriterion("is_bury =", value, "isBury");
			return (Criteria) this;
		}

		public Criteria andIsBuryNotEqualTo(Boolean value) {
			addCriterion("is_bury <>", value, "isBury");
			return (Criteria) this;
		}

		public Criteria andIsBuryGreaterThan(Boolean value) {
			addCriterion("is_bury >", value, "isBury");
			return (Criteria) this;
		}

		public Criteria andIsBuryGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_bury >=", value, "isBury");
			return (Criteria) this;
		}

		public Criteria andIsBuryLessThan(Boolean value) {
			addCriterion("is_bury <", value, "isBury");
			return (Criteria) this;
		}

		public Criteria andIsBuryLessThanOrEqualTo(Boolean value) {
			addCriterion("is_bury <=", value, "isBury");
			return (Criteria) this;
		}

		public Criteria andIsBuryIn(List<Boolean> values) {
			addCriterion("is_bury in", values, "isBury");
			return (Criteria) this;
		}

		public Criteria andIsBuryNotIn(List<Boolean> values) {
			addCriterion("is_bury not in", values, "isBury");
			return (Criteria) this;
		}

		public Criteria andIsBuryBetween(Boolean value1, Boolean value2) {
			addCriterion("is_bury between", value1, value2, "isBury");
			return (Criteria) this;
		}

		public Criteria andIsBuryNotBetween(Boolean value1, Boolean value2) {
			addCriterion("is_bury not between", value1, value2, "isBury");
			return (Criteria) this;
		}

		public Criteria andIsVisitGraveIsNull() {
			addCriterion("is_visit_grave is null");
			return (Criteria) this;
		}

		public Criteria andIsVisitGraveIsNotNull() {
			addCriterion("is_visit_grave is not null");
			return (Criteria) this;
		}

		public Criteria andIsVisitGraveEqualTo(Boolean value) {
			addCriterion("is_visit_grave =", value, "isVisitGrave");
			return (Criteria) this;
		}

		public Criteria andIsVisitGraveNotEqualTo(Boolean value) {
			addCriterion("is_visit_grave <>", value, "isVisitGrave");
			return (Criteria) this;
		}

		public Criteria andIsVisitGraveGreaterThan(Boolean value) {
			addCriterion("is_visit_grave >", value, "isVisitGrave");
			return (Criteria) this;
		}

		public Criteria andIsVisitGraveGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_visit_grave >=", value, "isVisitGrave");
			return (Criteria) this;
		}

		public Criteria andIsVisitGraveLessThan(Boolean value) {
			addCriterion("is_visit_grave <", value, "isVisitGrave");
			return (Criteria) this;
		}

		public Criteria andIsVisitGraveLessThanOrEqualTo(Boolean value) {
			addCriterion("is_visit_grave <=", value, "isVisitGrave");
			return (Criteria) this;
		}

		public Criteria andIsVisitGraveIn(List<Boolean> values) {
			addCriterion("is_visit_grave in", values, "isVisitGrave");
			return (Criteria) this;
		}

		public Criteria andIsVisitGraveNotIn(List<Boolean> values) {
			addCriterion("is_visit_grave not in", values, "isVisitGrave");
			return (Criteria) this;
		}

		public Criteria andIsVisitGraveBetween(Boolean value1, Boolean value2) {
			addCriterion("is_visit_grave between", value1, value2,
					"isVisitGrave");
			return (Criteria) this;
		}

		public Criteria andIsVisitGraveNotBetween(Boolean value1, Boolean value2) {
			addCriterion("is_visit_grave not between", value1, value2,
					"isVisitGrave");
			return (Criteria) this;
		}

		public Criteria andIsFreeParkingIsNull() {
			addCriterion("is_free_parking is null");
			return (Criteria) this;
		}

		public Criteria andIsFreeParkingIsNotNull() {
			addCriterion("is_free_parking is not null");
			return (Criteria) this;
		}

		public Criteria andIsFreeParkingEqualTo(Boolean value) {
			addCriterion("is_free_parking =", value, "isFreeParking");
			return (Criteria) this;
		}

		public Criteria andIsFreeParkingNotEqualTo(Boolean value) {
			addCriterion("is_free_parking <>", value, "isFreeParking");
			return (Criteria) this;
		}

		public Criteria andIsFreeParkingGreaterThan(Boolean value) {
			addCriterion("is_free_parking >", value, "isFreeParking");
			return (Criteria) this;
		}

		public Criteria andIsFreeParkingGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_free_parking >=", value, "isFreeParking");
			return (Criteria) this;
		}

		public Criteria andIsFreeParkingLessThan(Boolean value) {
			addCriterion("is_free_parking <", value, "isFreeParking");
			return (Criteria) this;
		}

		public Criteria andIsFreeParkingLessThanOrEqualTo(Boolean value) {
			addCriterion("is_free_parking <=", value, "isFreeParking");
			return (Criteria) this;
		}

		public Criteria andIsFreeParkingIn(List<Boolean> values) {
			addCriterion("is_free_parking in", values, "isFreeParking");
			return (Criteria) this;
		}

		public Criteria andIsFreeParkingNotIn(List<Boolean> values) {
			addCriterion("is_free_parking not in", values, "isFreeParking");
			return (Criteria) this;
		}

		public Criteria andIsFreeParkingBetween(Boolean value1, Boolean value2) {
			addCriterion("is_free_parking between", value1, value2,
					"isFreeParking");
			return (Criteria) this;
		}

		public Criteria andIsFreeParkingNotBetween(Boolean value1,
				Boolean value2) {
			addCriterion("is_free_parking not between", value1, value2,
					"isFreeParking");
			return (Criteria) this;
		}

		public Criteria andIsRestAreaIsNull() {
			addCriterion("is_rest_area is null");
			return (Criteria) this;
		}

		public Criteria andIsRestAreaIsNotNull() {
			addCriterion("is_rest_area is not null");
			return (Criteria) this;
		}

		public Criteria andIsRestAreaEqualTo(Boolean value) {
			addCriterion("is_rest_area =", value, "isRestArea");
			return (Criteria) this;
		}

		public Criteria andIsRestAreaNotEqualTo(Boolean value) {
			addCriterion("is_rest_area <>", value, "isRestArea");
			return (Criteria) this;
		}

		public Criteria andIsRestAreaGreaterThan(Boolean value) {
			addCriterion("is_rest_area >", value, "isRestArea");
			return (Criteria) this;
		}

		public Criteria andIsRestAreaGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_rest_area >=", value, "isRestArea");
			return (Criteria) this;
		}

		public Criteria andIsRestAreaLessThan(Boolean value) {
			addCriterion("is_rest_area <", value, "isRestArea");
			return (Criteria) this;
		}

		public Criteria andIsRestAreaLessThanOrEqualTo(Boolean value) {
			addCriterion("is_rest_area <=", value, "isRestArea");
			return (Criteria) this;
		}

		public Criteria andIsRestAreaIn(List<Boolean> values) {
			addCriterion("is_rest_area in", values, "isRestArea");
			return (Criteria) this;
		}

		public Criteria andIsRestAreaNotIn(List<Boolean> values) {
			addCriterion("is_rest_area not in", values, "isRestArea");
			return (Criteria) this;
		}

		public Criteria andIsRestAreaBetween(Boolean value1, Boolean value2) {
			addCriterion("is_rest_area between", value1, value2, "isRestArea");
			return (Criteria) this;
		}

		public Criteria andIsRestAreaNotBetween(Boolean value1, Boolean value2) {
			addCriterion("is_rest_area not between", value1, value2,
					"isRestArea");
			return (Criteria) this;
		}

		public Criteria andCoordinateIsNull() {
			addCriterion("coordinate is null");
			return (Criteria) this;
		}

		public Criteria andCoordinateIsNotNull() {
			addCriterion("coordinate is not null");
			return (Criteria) this;
		}

		public Criteria andCoordinateEqualTo(String value) {
			addCriterion("coordinate =", value, "coordinate");
			return (Criteria) this;
		}

		public Criteria andCoordinateNotEqualTo(String value) {
			addCriterion("coordinate <>", value, "coordinate");
			return (Criteria) this;
		}

		public Criteria andCoordinateGreaterThan(String value) {
			addCriterion("coordinate >", value, "coordinate");
			return (Criteria) this;
		}

		public Criteria andCoordinateGreaterThanOrEqualTo(String value) {
			addCriterion("coordinate >=", value, "coordinate");
			return (Criteria) this;
		}

		public Criteria andCoordinateLessThan(String value) {
			addCriterion("coordinate <", value, "coordinate");
			return (Criteria) this;
		}

		public Criteria andCoordinateLessThanOrEqualTo(String value) {
			addCriterion("coordinate <=", value, "coordinate");
			return (Criteria) this;
		}

		public Criteria andCoordinateLike(String value) {
			addCriterion("coordinate like", value, "coordinate");
			return (Criteria) this;
		}

		public Criteria andCoordinateNotLike(String value) {
			addCriterion("coordinate not like", value, "coordinate");
			return (Criteria) this;
		}

		public Criteria andCoordinateIn(List<String> values) {
			addCriterion("coordinate in", values, "coordinate");
			return (Criteria) this;
		}

		public Criteria andCoordinateNotIn(List<String> values) {
			addCriterion("coordinate not in", values, "coordinate");
			return (Criteria) this;
		}

		public Criteria andCoordinateBetween(String value1, String value2) {
			addCriterion("coordinate between", value1, value2, "coordinate");
			return (Criteria) this;
		}

		public Criteria andCoordinateNotBetween(String value1, String value2) {
			addCriterion("coordinate not between", value1, value2, "coordinate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_cemetery
	 * @mbggenerated  Wed Oct 26 22:19:56 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_company
     *
     * @mbggenerated do_not_delete_during_merge Wed Aug 10 22:04:00 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}