package com.gmzj.entity;

import java.io.Serializable;

public class Cemetery implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.id
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.name
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.type
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.score
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private String score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.average
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private Float average;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.price
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private Long price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.status
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.address
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.slogan
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private String slogan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.scale
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private Integer scale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.prov
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private String prov;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.city
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.dist
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private String dist;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.distance
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private Integer distance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.bespeak
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private Integer bespeak;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.view_num
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private Integer viewNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.approval_dep
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private String approvalDep;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.characteristic
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private String characteristic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.preferential
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private String preferential;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.authentication
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private Boolean authentication;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.discount
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private Boolean discount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.retain_ashes
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private String retainAshes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.img_url
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private String imgUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.introduce
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private String introduce;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cemetery.coordinate
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	private String coordinate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.id
	 * @return  the value of t_cemetery.id
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.id
	 * @param id  the value for t_cemetery.id
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.name
	 * @return  the value of t_cemetery.name
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.name
	 * @param name  the value for t_cemetery.name
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.type
	 * @return  the value of t_cemetery.type
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.type
	 * @param type  the value for t_cemetery.type
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.score
	 * @return  the value of t_cemetery.score
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public String getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.score
	 * @param score  the value for t_cemetery.score
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setScore(String score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.average
	 * @return  the value of t_cemetery.average
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public Float getAverage() {
		return average;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.average
	 * @param average  the value for t_cemetery.average
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setAverage(Float average) {
		this.average = average;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.price
	 * @return  the value of t_cemetery.price
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public Long getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.price
	 * @param price  the value for t_cemetery.price
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setPrice(Long price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.status
	 * @return  the value of t_cemetery.status
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.status
	 * @param status  the value for t_cemetery.status
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.address
	 * @return  the value of t_cemetery.address
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.address
	 * @param address  the value for t_cemetery.address
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.slogan
	 * @return  the value of t_cemetery.slogan
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public String getSlogan() {
		return slogan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.slogan
	 * @param slogan  the value for t_cemetery.slogan
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setSlogan(String slogan) {
		this.slogan = slogan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.scale
	 * @return  the value of t_cemetery.scale
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public Integer getScale() {
		return scale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.scale
	 * @param scale  the value for t_cemetery.scale
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setScale(Integer scale) {
		this.scale = scale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.prov
	 * @return  the value of t_cemetery.prov
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public String getProv() {
		return prov;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.prov
	 * @param prov  the value for t_cemetery.prov
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setProv(String prov) {
		this.prov = prov;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.city
	 * @return  the value of t_cemetery.city
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.city
	 * @param city  the value for t_cemetery.city
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.dist
	 * @return  the value of t_cemetery.dist
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public String getDist() {
		return dist;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.dist
	 * @param dist  the value for t_cemetery.dist
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setDist(String dist) {
		this.dist = dist;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.distance
	 * @return  the value of t_cemetery.distance
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public Integer getDistance() {
		return distance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.distance
	 * @param distance  the value for t_cemetery.distance
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setDistance(Integer distance) {
		this.distance = distance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.bespeak
	 * @return  the value of t_cemetery.bespeak
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public Integer getBespeak() {
		return bespeak;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.bespeak
	 * @param bespeak  the value for t_cemetery.bespeak
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setBespeak(Integer bespeak) {
		this.bespeak = bespeak;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.view_num
	 * @return  the value of t_cemetery.view_num
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public Integer getViewNum() {
		return viewNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.view_num
	 * @param viewNum  the value for t_cemetery.view_num
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setViewNum(Integer viewNum) {
		this.viewNum = viewNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.approval_dep
	 * @return  the value of t_cemetery.approval_dep
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public String getApprovalDep() {
		return approvalDep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.approval_dep
	 * @param approvalDep  the value for t_cemetery.approval_dep
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setApprovalDep(String approvalDep) {
		this.approvalDep = approvalDep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.characteristic
	 * @return  the value of t_cemetery.characteristic
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public String getCharacteristic() {
		return characteristic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.characteristic
	 * @param characteristic  the value for t_cemetery.characteristic
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setCharacteristic(String characteristic) {
		this.characteristic = characteristic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.preferential
	 * @return  the value of t_cemetery.preferential
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public String getPreferential() {
		return preferential;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.preferential
	 * @param preferential  the value for t_cemetery.preferential
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setPreferential(String preferential) {
		this.preferential = preferential;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.authentication
	 * @return  the value of t_cemetery.authentication
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public Boolean getAuthentication() {
		return authentication;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.authentication
	 * @param authentication  the value for t_cemetery.authentication
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setAuthentication(Boolean authentication) {
		this.authentication = authentication;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.discount
	 * @return  the value of t_cemetery.discount
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public Boolean getDiscount() {
		return discount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.discount
	 * @param discount  the value for t_cemetery.discount
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setDiscount(Boolean discount) {
		this.discount = discount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.retain_ashes
	 * @return  the value of t_cemetery.retain_ashes
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public String getRetainAshes() {
		return retainAshes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.retain_ashes
	 * @param retainAshes  the value for t_cemetery.retain_ashes
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setRetainAshes(String retainAshes) {
		this.retainAshes = retainAshes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.img_url
	 * @return  the value of t_cemetery.img_url
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public String getImgUrl() {
		return imgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.img_url
	 * @param imgUrl  the value for t_cemetery.img_url
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.introduce
	 * @return  the value of t_cemetery.introduce
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public String getIntroduce() {
		return introduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.introduce
	 * @param introduce  the value for t_cemetery.introduce
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setIntroduce(String introduce) {
		this.introduce = introduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cemetery.coordinate
	 * @return  the value of t_cemetery.coordinate
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public String getCoordinate() {
		return coordinate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cemetery.coordinate
	 * @param coordinate  the value for t_cemetery.coordinate
	 * @mbggenerated  Sat Sep 17 22:58:10 CST 2016
	 */
	public void setCoordinate(String coordinate) {
		this.coordinate = coordinate;
	}

	private static final long serialVersionUID = 1L;
	public static enum ComStat implements IntEnum<ComStat> {
		normal("1", "正常"), invalid("0", "失效");

		private final String index;
		private final String name;
		private ComStat(String index, String name) {
			this.index = index;
			this.name = name;
		}

		public static String getName(String index) {
			for (ComStat e : ComStat.values()) {
				if (e.getIndex().equals(index)) {
					return e.name;
				}
			}
			return null;
		}

		public String getName() {
			return name;
		}

		public String getIndex() {
			// TODO Auto-generated method stub
			return index;
		}
	}

	public String getStatDescribe(){
		return ComStat.getName(this.status);
	}

	public static enum ComType implements IntEnum<ComType>{
		fw01("01","公墓陵园"), fw02("02", "殡仪服务"), fw03("03", "风水堪舆");

		private final String index;
		private final String name;
		private ComType(String index, String name) {
			this.index = index;
			this.name = name;
		}

		public static String getName(String index) {
			for (ComType e : ComType.values()) {
				if (e.getIndex().equals(index)) {
					return e.name;
				}
			}
			return null;
		}

		public String getName() {
			return name;
		}

		public String getIndex() {
			// TODO Auto-generated method stub
			return index;
		}
	}
	
	public String getTypeDescribe(){
		return ComType.getName(this.type);
	}
}