package com.gmzj.entity;

import java.util.ArrayList;
import java.util.List;

public class CemTypeExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_cem_type
	 * @mbggenerated  Tue Oct 18 22:53:51 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_cem_type
	 * @mbggenerated  Tue Oct 18 22:53:51 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_cem_type
	 * @mbggenerated  Tue Oct 18 22:53:51 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cem_type
	 * @mbggenerated  Tue Oct 18 22:53:51 CST 2016
	 */
	public CemTypeExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cem_type
	 * @mbggenerated  Tue Oct 18 22:53:51 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cem_type
	 * @mbggenerated  Tue Oct 18 22:53:51 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cem_type
	 * @mbggenerated  Tue Oct 18 22:53:51 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cem_type
	 * @mbggenerated  Tue Oct 18 22:53:51 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cem_type
	 * @mbggenerated  Tue Oct 18 22:53:51 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cem_type
	 * @mbggenerated  Tue Oct 18 22:53:51 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cem_type
	 * @mbggenerated  Tue Oct 18 22:53:51 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cem_type
	 * @mbggenerated  Tue Oct 18 22:53:51 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cem_type
	 * @mbggenerated  Tue Oct 18 22:53:51 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cem_type
	 * @mbggenerated  Tue Oct 18 22:53:51 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_cem_type
	 * @mbggenerated  Tue Oct 18 22:53:51 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andCemIdIsNull() {
			addCriterion("cem_id is null");
			return (Criteria) this;
		}

		public Criteria andCemIdIsNotNull() {
			addCriterion("cem_id is not null");
			return (Criteria) this;
		}

		public Criteria andCemIdEqualTo(Integer value) {
			addCriterion("cem_id =", value, "cemId");
			return (Criteria) this;
		}

		public Criteria andCemIdNotEqualTo(Integer value) {
			addCriterion("cem_id <>", value, "cemId");
			return (Criteria) this;
		}

		public Criteria andCemIdGreaterThan(Integer value) {
			addCriterion("cem_id >", value, "cemId");
			return (Criteria) this;
		}

		public Criteria andCemIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("cem_id >=", value, "cemId");
			return (Criteria) this;
		}

		public Criteria andCemIdLessThan(Integer value) {
			addCriterion("cem_id <", value, "cemId");
			return (Criteria) this;
		}

		public Criteria andCemIdLessThanOrEqualTo(Integer value) {
			addCriterion("cem_id <=", value, "cemId");
			return (Criteria) this;
		}

		public Criteria andCemIdIn(List<Integer> values) {
			addCriterion("cem_id in", values, "cemId");
			return (Criteria) this;
		}

		public Criteria andCemIdNotIn(List<Integer> values) {
			addCriterion("cem_id not in", values, "cemId");
			return (Criteria) this;
		}

		public Criteria andCemIdBetween(Integer value1, Integer value2) {
			addCriterion("cem_id between", value1, value2, "cemId");
			return (Criteria) this;
		}

		public Criteria andCemIdNotBetween(Integer value1, Integer value2) {
			addCriterion("cem_id not between", value1, value2, "cemId");
			return (Criteria) this;
		}

		public Criteria andZoneIdIsNull() {
			addCriterion("zone_id is null");
			return (Criteria) this;
		}

		public Criteria andZoneIdIsNotNull() {
			addCriterion("zone_id is not null");
			return (Criteria) this;
		}

		public Criteria andZoneIdEqualTo(Integer value) {
			addCriterion("zone_id =", value, "zoneId");
			return (Criteria) this;
		}

		public Criteria andZoneIdNotEqualTo(Integer value) {
			addCriterion("zone_id <>", value, "zoneId");
			return (Criteria) this;
		}

		public Criteria andZoneIdGreaterThan(Integer value) {
			addCriterion("zone_id >", value, "zoneId");
			return (Criteria) this;
		}

		public Criteria andZoneIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("zone_id >=", value, "zoneId");
			return (Criteria) this;
		}

		public Criteria andZoneIdLessThan(Integer value) {
			addCriterion("zone_id <", value, "zoneId");
			return (Criteria) this;
		}

		public Criteria andZoneIdLessThanOrEqualTo(Integer value) {
			addCriterion("zone_id <=", value, "zoneId");
			return (Criteria) this;
		}

		public Criteria andZoneIdIn(List<Integer> values) {
			addCriterion("zone_id in", values, "zoneId");
			return (Criteria) this;
		}

		public Criteria andZoneIdNotIn(List<Integer> values) {
			addCriterion("zone_id not in", values, "zoneId");
			return (Criteria) this;
		}

		public Criteria andZoneIdBetween(Integer value1, Integer value2) {
			addCriterion("zone_id between", value1, value2, "zoneId");
			return (Criteria) this;
		}

		public Criteria andZoneIdNotBetween(Integer value1, Integer value2) {
			addCriterion("zone_id not between", value1, value2, "zoneId");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andOrigPriceIsNull() {
			addCriterion("orig_price is null");
			return (Criteria) this;
		}

		public Criteria andOrigPriceIsNotNull() {
			addCriterion("orig_price is not null");
			return (Criteria) this;
		}

		public Criteria andOrigPriceEqualTo(Long value) {
			addCriterion("orig_price =", value, "origPrice");
			return (Criteria) this;
		}

		public Criteria andOrigPriceNotEqualTo(Long value) {
			addCriterion("orig_price <>", value, "origPrice");
			return (Criteria) this;
		}

		public Criteria andOrigPriceGreaterThan(Long value) {
			addCriterion("orig_price >", value, "origPrice");
			return (Criteria) this;
		}

		public Criteria andOrigPriceGreaterThanOrEqualTo(Long value) {
			addCriterion("orig_price >=", value, "origPrice");
			return (Criteria) this;
		}

		public Criteria andOrigPriceLessThan(Long value) {
			addCriterion("orig_price <", value, "origPrice");
			return (Criteria) this;
		}

		public Criteria andOrigPriceLessThanOrEqualTo(Long value) {
			addCriterion("orig_price <=", value, "origPrice");
			return (Criteria) this;
		}

		public Criteria andOrigPriceIn(List<Long> values) {
			addCriterion("orig_price in", values, "origPrice");
			return (Criteria) this;
		}

		public Criteria andOrigPriceNotIn(List<Long> values) {
			addCriterion("orig_price not in", values, "origPrice");
			return (Criteria) this;
		}

		public Criteria andOrigPriceBetween(Long value1, Long value2) {
			addCriterion("orig_price between", value1, value2, "origPrice");
			return (Criteria) this;
		}

		public Criteria andOrigPriceNotBetween(Long value1, Long value2) {
			addCriterion("orig_price not between", value1, value2, "origPrice");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(Long value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(Long value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(Long value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Long value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(Long value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(Long value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<Long> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<Long> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(Long value1, Long value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(Long value1, Long value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andIsDisPriceIsNull() {
			addCriterion("is_dis_price is null");
			return (Criteria) this;
		}

		public Criteria andIsDisPriceIsNotNull() {
			addCriterion("is_dis_price is not null");
			return (Criteria) this;
		}

		public Criteria andIsDisPriceEqualTo(Boolean value) {
			addCriterion("is_dis_price =", value, "isDisPrice");
			return (Criteria) this;
		}

		public Criteria andIsDisPriceNotEqualTo(Boolean value) {
			addCriterion("is_dis_price <>", value, "isDisPrice");
			return (Criteria) this;
		}

		public Criteria andIsDisPriceGreaterThan(Boolean value) {
			addCriterion("is_dis_price >", value, "isDisPrice");
			return (Criteria) this;
		}

		public Criteria andIsDisPriceGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_dis_price >=", value, "isDisPrice");
			return (Criteria) this;
		}

		public Criteria andIsDisPriceLessThan(Boolean value) {
			addCriterion("is_dis_price <", value, "isDisPrice");
			return (Criteria) this;
		}

		public Criteria andIsDisPriceLessThanOrEqualTo(Boolean value) {
			addCriterion("is_dis_price <=", value, "isDisPrice");
			return (Criteria) this;
		}

		public Criteria andIsDisPriceIn(List<Boolean> values) {
			addCriterion("is_dis_price in", values, "isDisPrice");
			return (Criteria) this;
		}

		public Criteria andIsDisPriceNotIn(List<Boolean> values) {
			addCriterion("is_dis_price not in", values, "isDisPrice");
			return (Criteria) this;
		}

		public Criteria andIsDisPriceBetween(Boolean value1, Boolean value2) {
			addCriterion("is_dis_price between", value1, value2, "isDisPrice");
			return (Criteria) this;
		}

		public Criteria andIsDisPriceNotBetween(Boolean value1, Boolean value2) {
			addCriterion("is_dis_price not between", value1, value2,
					"isDisPrice");
			return (Criteria) this;
		}

		public Criteria andMaterialIsNull() {
			addCriterion("material is null");
			return (Criteria) this;
		}

		public Criteria andMaterialIsNotNull() {
			addCriterion("material is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialEqualTo(String value) {
			addCriterion("material =", value, "material");
			return (Criteria) this;
		}

		public Criteria andMaterialNotEqualTo(String value) {
			addCriterion("material <>", value, "material");
			return (Criteria) this;
		}

		public Criteria andMaterialGreaterThan(String value) {
			addCriterion("material >", value, "material");
			return (Criteria) this;
		}

		public Criteria andMaterialGreaterThanOrEqualTo(String value) {
			addCriterion("material >=", value, "material");
			return (Criteria) this;
		}

		public Criteria andMaterialLessThan(String value) {
			addCriterion("material <", value, "material");
			return (Criteria) this;
		}

		public Criteria andMaterialLessThanOrEqualTo(String value) {
			addCriterion("material <=", value, "material");
			return (Criteria) this;
		}

		public Criteria andMaterialLike(String value) {
			addCriterion("material like", value, "material");
			return (Criteria) this;
		}

		public Criteria andMaterialNotLike(String value) {
			addCriterion("material not like", value, "material");
			return (Criteria) this;
		}

		public Criteria andMaterialIn(List<String> values) {
			addCriterion("material in", values, "material");
			return (Criteria) this;
		}

		public Criteria andMaterialNotIn(List<String> values) {
			addCriterion("material not in", values, "material");
			return (Criteria) this;
		}

		public Criteria andMaterialBetween(String value1, String value2) {
			addCriterion("material between", value1, value2, "material");
			return (Criteria) this;
		}

		public Criteria andMaterialNotBetween(String value1, String value2) {
			addCriterion("material not between", value1, value2, "material");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(String value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(String value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(String value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(String value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(String value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(String value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLike(String value) {
			addCriterion("type like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotLike(String value) {
			addCriterion("type not like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<String> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<String> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(String value1, String value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(String value1, String value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andColoursIsNull() {
			addCriterion("colours is null");
			return (Criteria) this;
		}

		public Criteria andColoursIsNotNull() {
			addCriterion("colours is not null");
			return (Criteria) this;
		}

		public Criteria andColoursEqualTo(String value) {
			addCriterion("colours =", value, "colours");
			return (Criteria) this;
		}

		public Criteria andColoursNotEqualTo(String value) {
			addCriterion("colours <>", value, "colours");
			return (Criteria) this;
		}

		public Criteria andColoursGreaterThan(String value) {
			addCriterion("colours >", value, "colours");
			return (Criteria) this;
		}

		public Criteria andColoursGreaterThanOrEqualTo(String value) {
			addCriterion("colours >=", value, "colours");
			return (Criteria) this;
		}

		public Criteria andColoursLessThan(String value) {
			addCriterion("colours <", value, "colours");
			return (Criteria) this;
		}

		public Criteria andColoursLessThanOrEqualTo(String value) {
			addCriterion("colours <=", value, "colours");
			return (Criteria) this;
		}

		public Criteria andColoursLike(String value) {
			addCriterion("colours like", value, "colours");
			return (Criteria) this;
		}

		public Criteria andColoursNotLike(String value) {
			addCriterion("colours not like", value, "colours");
			return (Criteria) this;
		}

		public Criteria andColoursIn(List<String> values) {
			addCriterion("colours in", values, "colours");
			return (Criteria) this;
		}

		public Criteria andColoursNotIn(List<String> values) {
			addCriterion("colours not in", values, "colours");
			return (Criteria) this;
		}

		public Criteria andColoursBetween(String value1, String value2) {
			addCriterion("colours between", value1, value2, "colours");
			return (Criteria) this;
		}

		public Criteria andColoursNotBetween(String value1, String value2) {
			addCriterion("colours not between", value1, value2, "colours");
			return (Criteria) this;
		}

		public Criteria andEnjoyIsNull() {
			addCriterion("enjoy is null");
			return (Criteria) this;
		}

		public Criteria andEnjoyIsNotNull() {
			addCriterion("enjoy is not null");
			return (Criteria) this;
		}

		public Criteria andEnjoyEqualTo(Boolean value) {
			addCriterion("enjoy =", value, "enjoy");
			return (Criteria) this;
		}

		public Criteria andEnjoyNotEqualTo(Boolean value) {
			addCriterion("enjoy <>", value, "enjoy");
			return (Criteria) this;
		}

		public Criteria andEnjoyGreaterThan(Boolean value) {
			addCriterion("enjoy >", value, "enjoy");
			return (Criteria) this;
		}

		public Criteria andEnjoyGreaterThanOrEqualTo(Boolean value) {
			addCriterion("enjoy >=", value, "enjoy");
			return (Criteria) this;
		}

		public Criteria andEnjoyLessThan(Boolean value) {
			addCriterion("enjoy <", value, "enjoy");
			return (Criteria) this;
		}

		public Criteria andEnjoyLessThanOrEqualTo(Boolean value) {
			addCriterion("enjoy <=", value, "enjoy");
			return (Criteria) this;
		}

		public Criteria andEnjoyIn(List<Boolean> values) {
			addCriterion("enjoy in", values, "enjoy");
			return (Criteria) this;
		}

		public Criteria andEnjoyNotIn(List<Boolean> values) {
			addCriterion("enjoy not in", values, "enjoy");
			return (Criteria) this;
		}

		public Criteria andEnjoyBetween(Boolean value1, Boolean value2) {
			addCriterion("enjoy between", value1, value2, "enjoy");
			return (Criteria) this;
		}

		public Criteria andEnjoyNotBetween(Boolean value1, Boolean value2) {
			addCriterion("enjoy not between", value1, value2, "enjoy");
			return (Criteria) this;
		}

		public Criteria andSpecialIsNull() {
			addCriterion("special is null");
			return (Criteria) this;
		}

		public Criteria andSpecialIsNotNull() {
			addCriterion("special is not null");
			return (Criteria) this;
		}

		public Criteria andSpecialEqualTo(Boolean value) {
			addCriterion("special =", value, "special");
			return (Criteria) this;
		}

		public Criteria andSpecialNotEqualTo(Boolean value) {
			addCriterion("special <>", value, "special");
			return (Criteria) this;
		}

		public Criteria andSpecialGreaterThan(Boolean value) {
			addCriterion("special >", value, "special");
			return (Criteria) this;
		}

		public Criteria andSpecialGreaterThanOrEqualTo(Boolean value) {
			addCriterion("special >=", value, "special");
			return (Criteria) this;
		}

		public Criteria andSpecialLessThan(Boolean value) {
			addCriterion("special <", value, "special");
			return (Criteria) this;
		}

		public Criteria andSpecialLessThanOrEqualTo(Boolean value) {
			addCriterion("special <=", value, "special");
			return (Criteria) this;
		}

		public Criteria andSpecialIn(List<Boolean> values) {
			addCriterion("special in", values, "special");
			return (Criteria) this;
		}

		public Criteria andSpecialNotIn(List<Boolean> values) {
			addCriterion("special not in", values, "special");
			return (Criteria) this;
		}

		public Criteria andSpecialBetween(Boolean value1, Boolean value2) {
			addCriterion("special between", value1, value2, "special");
			return (Criteria) this;
		}

		public Criteria andSpecialNotBetween(Boolean value1, Boolean value2) {
			addCriterion("special not between", value1, value2, "special");
			return (Criteria) this;
		}

		public Criteria andSpecialNumIsNull() {
			addCriterion("special_num is null");
			return (Criteria) this;
		}

		public Criteria andSpecialNumIsNotNull() {
			addCriterion("special_num is not null");
			return (Criteria) this;
		}

		public Criteria andSpecialNumEqualTo(Integer value) {
			addCriterion("special_num =", value, "specialNum");
			return (Criteria) this;
		}

		public Criteria andSpecialNumNotEqualTo(Integer value) {
			addCriterion("special_num <>", value, "specialNum");
			return (Criteria) this;
		}

		public Criteria andSpecialNumGreaterThan(Integer value) {
			addCriterion("special_num >", value, "specialNum");
			return (Criteria) this;
		}

		public Criteria andSpecialNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("special_num >=", value, "specialNum");
			return (Criteria) this;
		}

		public Criteria andSpecialNumLessThan(Integer value) {
			addCriterion("special_num <", value, "specialNum");
			return (Criteria) this;
		}

		public Criteria andSpecialNumLessThanOrEqualTo(Integer value) {
			addCriterion("special_num <=", value, "specialNum");
			return (Criteria) this;
		}

		public Criteria andSpecialNumIn(List<Integer> values) {
			addCriterion("special_num in", values, "specialNum");
			return (Criteria) this;
		}

		public Criteria andSpecialNumNotIn(List<Integer> values) {
			addCriterion("special_num not in", values, "specialNum");
			return (Criteria) this;
		}

		public Criteria andSpecialNumBetween(Integer value1, Integer value2) {
			addCriterion("special_num between", value1, value2, "specialNum");
			return (Criteria) this;
		}

		public Criteria andSpecialNumNotBetween(Integer value1, Integer value2) {
			addCriterion("special_num not between", value1, value2,
					"specialNum");
			return (Criteria) this;
		}

		public Criteria andDirectionIsNull() {
			addCriterion("direction is null");
			return (Criteria) this;
		}

		public Criteria andDirectionIsNotNull() {
			addCriterion("direction is not null");
			return (Criteria) this;
		}

		public Criteria andDirectionEqualTo(String value) {
			addCriterion("direction =", value, "direction");
			return (Criteria) this;
		}

		public Criteria andDirectionNotEqualTo(String value) {
			addCriterion("direction <>", value, "direction");
			return (Criteria) this;
		}

		public Criteria andDirectionGreaterThan(String value) {
			addCriterion("direction >", value, "direction");
			return (Criteria) this;
		}

		public Criteria andDirectionGreaterThanOrEqualTo(String value) {
			addCriterion("direction >=", value, "direction");
			return (Criteria) this;
		}

		public Criteria andDirectionLessThan(String value) {
			addCriterion("direction <", value, "direction");
			return (Criteria) this;
		}

		public Criteria andDirectionLessThanOrEqualTo(String value) {
			addCriterion("direction <=", value, "direction");
			return (Criteria) this;
		}

		public Criteria andDirectionLike(String value) {
			addCriterion("direction like", value, "direction");
			return (Criteria) this;
		}

		public Criteria andDirectionNotLike(String value) {
			addCriterion("direction not like", value, "direction");
			return (Criteria) this;
		}

		public Criteria andDirectionIn(List<String> values) {
			addCriterion("direction in", values, "direction");
			return (Criteria) this;
		}

		public Criteria andDirectionNotIn(List<String> values) {
			addCriterion("direction not in", values, "direction");
			return (Criteria) this;
		}

		public Criteria andDirectionBetween(String value1, String value2) {
			addCriterion("direction between", value1, value2, "direction");
			return (Criteria) this;
		}

		public Criteria andDirectionNotBetween(String value1, String value2) {
			addCriterion("direction not between", value1, value2, "direction");
			return (Criteria) this;
		}

		public Criteria andFollowNumIsNull() {
			addCriterion("follow_num is null");
			return (Criteria) this;
		}

		public Criteria andFollowNumIsNotNull() {
			addCriterion("follow_num is not null");
			return (Criteria) this;
		}

		public Criteria andFollowNumEqualTo(Integer value) {
			addCriterion("follow_num =", value, "followNum");
			return (Criteria) this;
		}

		public Criteria andFollowNumNotEqualTo(Integer value) {
			addCriterion("follow_num <>", value, "followNum");
			return (Criteria) this;
		}

		public Criteria andFollowNumGreaterThan(Integer value) {
			addCriterion("follow_num >", value, "followNum");
			return (Criteria) this;
		}

		public Criteria andFollowNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("follow_num >=", value, "followNum");
			return (Criteria) this;
		}

		public Criteria andFollowNumLessThan(Integer value) {
			addCriterion("follow_num <", value, "followNum");
			return (Criteria) this;
		}

		public Criteria andFollowNumLessThanOrEqualTo(Integer value) {
			addCriterion("follow_num <=", value, "followNum");
			return (Criteria) this;
		}

		public Criteria andFollowNumIn(List<Integer> values) {
			addCriterion("follow_num in", values, "followNum");
			return (Criteria) this;
		}

		public Criteria andFollowNumNotIn(List<Integer> values) {
			addCriterion("follow_num not in", values, "followNum");
			return (Criteria) this;
		}

		public Criteria andFollowNumBetween(Integer value1, Integer value2) {
			addCriterion("follow_num between", value1, value2, "followNum");
			return (Criteria) this;
		}

		public Criteria andFollowNumNotBetween(Integer value1, Integer value2) {
			addCriterion("follow_num not between", value1, value2, "followNum");
			return (Criteria) this;
		}

		public Criteria andNumIsNull() {
			addCriterion("num is null");
			return (Criteria) this;
		}

		public Criteria andNumIsNotNull() {
			addCriterion("num is not null");
			return (Criteria) this;
		}

		public Criteria andNumEqualTo(String value) {
			addCriterion("num =", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotEqualTo(String value) {
			addCriterion("num <>", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumGreaterThan(String value) {
			addCriterion("num >", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumGreaterThanOrEqualTo(String value) {
			addCriterion("num >=", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumLessThan(String value) {
			addCriterion("num <", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumLessThanOrEqualTo(String value) {
			addCriterion("num <=", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumLike(String value) {
			addCriterion("num like", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotLike(String value) {
			addCriterion("num not like", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumIn(List<String> values) {
			addCriterion("num in", values, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotIn(List<String> values) {
			addCriterion("num not in", values, "num");
			return (Criteria) this;
		}

		public Criteria andNumBetween(String value1, String value2) {
			addCriterion("num between", value1, value2, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotBetween(String value1, String value2) {
			addCriterion("num not between", value1, value2, "num");
			return (Criteria) this;
		}

		public Criteria andFeatureIsNull() {
			addCriterion("feature is null");
			return (Criteria) this;
		}

		public Criteria andFeatureIsNotNull() {
			addCriterion("feature is not null");
			return (Criteria) this;
		}

		public Criteria andFeatureEqualTo(String value) {
			addCriterion("feature =", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureNotEqualTo(String value) {
			addCriterion("feature <>", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureGreaterThan(String value) {
			addCriterion("feature >", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureGreaterThanOrEqualTo(String value) {
			addCriterion("feature >=", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureLessThan(String value) {
			addCriterion("feature <", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureLessThanOrEqualTo(String value) {
			addCriterion("feature <=", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureLike(String value) {
			addCriterion("feature like", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureNotLike(String value) {
			addCriterion("feature not like", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureIn(List<String> values) {
			addCriterion("feature in", values, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureNotIn(List<String> values) {
			addCriterion("feature not in", values, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureBetween(String value1, String value2) {
			addCriterion("feature between", value1, value2, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureNotBetween(String value1, String value2) {
			addCriterion("feature not between", value1, value2, "feature");
			return (Criteria) this;
		}

		public Criteria andStatIsNull() {
			addCriterion("stat is null");
			return (Criteria) this;
		}

		public Criteria andStatIsNotNull() {
			addCriterion("stat is not null");
			return (Criteria) this;
		}

		public Criteria andStatEqualTo(String value) {
			addCriterion("stat =", value, "stat");
			return (Criteria) this;
		}

		public Criteria andStatNotEqualTo(String value) {
			addCriterion("stat <>", value, "stat");
			return (Criteria) this;
		}

		public Criteria andStatGreaterThan(String value) {
			addCriterion("stat >", value, "stat");
			return (Criteria) this;
		}

		public Criteria andStatGreaterThanOrEqualTo(String value) {
			addCriterion("stat >=", value, "stat");
			return (Criteria) this;
		}

		public Criteria andStatLessThan(String value) {
			addCriterion("stat <", value, "stat");
			return (Criteria) this;
		}

		public Criteria andStatLessThanOrEqualTo(String value) {
			addCriterion("stat <=", value, "stat");
			return (Criteria) this;
		}

		public Criteria andStatLike(String value) {
			addCriterion("stat like", value, "stat");
			return (Criteria) this;
		}

		public Criteria andStatNotLike(String value) {
			addCriterion("stat not like", value, "stat");
			return (Criteria) this;
		}

		public Criteria andStatIn(List<String> values) {
			addCriterion("stat in", values, "stat");
			return (Criteria) this;
		}

		public Criteria andStatNotIn(List<String> values) {
			addCriterion("stat not in", values, "stat");
			return (Criteria) this;
		}

		public Criteria andStatBetween(String value1, String value2) {
			addCriterion("stat between", value1, value2, "stat");
			return (Criteria) this;
		}

		public Criteria andStatNotBetween(String value1, String value2) {
			addCriterion("stat not between", value1, value2, "stat");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_cem_type
	 * @mbggenerated  Tue Oct 18 22:53:51 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cem_type
     *
     * @mbggenerated do_not_delete_during_merge Fri Oct 07 20:18:55 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}