package com.gmzj.entity;

import java.util.Date;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.id
     *
     * @mbggenerated Mon Sep 05 22:01:29 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.title
     *
     * @mbggenerated Mon Sep 05 22:01:29 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.content
     *
     * @mbggenerated Mon Sep 05 22:01:29 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.time
     *
     * @mbggenerated Mon Sep 05 22:01:29 CST 2016
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.imgUrl
     *
     * @mbggenerated Mon Sep 05 22:01:29 CST 2016
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.stat
     *
     * @mbggenerated Mon Sep 05 22:01:29 CST 2016
     */
    private String stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.id
     *
     * @return the value of t_news.id
     *
     * @mbggenerated Mon Sep 05 22:01:29 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.id
     *
     * @param id the value for t_news.id
     *
     * @mbggenerated Mon Sep 05 22:01:29 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.title
     *
     * @return the value of t_news.title
     *
     * @mbggenerated Mon Sep 05 22:01:29 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.title
     *
     * @param title the value for t_news.title
     *
     * @mbggenerated Mon Sep 05 22:01:29 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.content
     *
     * @return the value of t_news.content
     *
     * @mbggenerated Mon Sep 05 22:01:29 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.content
     *
     * @param content the value for t_news.content
     *
     * @mbggenerated Mon Sep 05 22:01:29 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.time
     *
     * @return the value of t_news.time
     *
     * @mbggenerated Mon Sep 05 22:01:29 CST 2016
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.time
     *
     * @param time the value for t_news.time
     *
     * @mbggenerated Mon Sep 05 22:01:29 CST 2016
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.imgUrl
     *
     * @return the value of t_news.imgUrl
     *
     * @mbggenerated Mon Sep 05 22:01:29 CST 2016
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.imgUrl
     *
     * @param imgurl the value for t_news.imgUrl
     *
     * @mbggenerated Mon Sep 05 22:01:29 CST 2016
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.stat
     *
     * @return the value of t_news.stat
     *
     * @mbggenerated Mon Sep 05 22:01:29 CST 2016
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.stat
     *
     * @param stat the value for t_news.stat
     *
     * @mbggenerated Mon Sep 05 22:01:29 CST 2016
     */
    public void setStat(String stat) {
        this.stat = stat;
    }
}