package com.gmzj.entity;

import java.util.Date;

import com.gmzj.entity.Company.ComStat;

public class News {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news.id
	 * @mbggenerated  Wed Sep 07 22:49:06 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news.title
	 * @mbggenerated  Wed Sep 07 22:49:06 CST 2016
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news.content
	 * @mbggenerated  Wed Sep 07 22:49:06 CST 2016
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news.time
	 * @mbggenerated  Wed Sep 07 22:49:06 CST 2016
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news.imgUrl
	 * @mbggenerated  Wed Sep 07 22:49:06 CST 2016
	 */
	private String imgurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news.status
	 * @mbggenerated  Wed Sep 07 22:49:06 CST 2016
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news.id
	 * @return  the value of t_news.id
	 * @mbggenerated  Wed Sep 07 22:49:06 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news.id
	 * @param id  the value for t_news.id
	 * @mbggenerated  Wed Sep 07 22:49:06 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news.title
	 * @return  the value of t_news.title
	 * @mbggenerated  Wed Sep 07 22:49:06 CST 2016
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news.title
	 * @param title  the value for t_news.title
	 * @mbggenerated  Wed Sep 07 22:49:06 CST 2016
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news.content
	 * @return  the value of t_news.content
	 * @mbggenerated  Wed Sep 07 22:49:06 CST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news.content
	 * @param content  the value for t_news.content
	 * @mbggenerated  Wed Sep 07 22:49:06 CST 2016
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news.time
	 * @return  the value of t_news.time
	 * @mbggenerated  Wed Sep 07 22:49:06 CST 2016
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news.time
	 * @param time  the value for t_news.time
	 * @mbggenerated  Wed Sep 07 22:49:06 CST 2016
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news.imgUrl
	 * @return  the value of t_news.imgUrl
	 * @mbggenerated  Wed Sep 07 22:49:06 CST 2016
	 */
	public String getImgurl() {
		return imgurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news.imgUrl
	 * @param imgurl  the value for t_news.imgUrl
	 * @mbggenerated  Wed Sep 07 22:49:06 CST 2016
	 */
	public void setImgurl(String imgurl) {
		this.imgurl = imgurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news.status
	 * @return  the value of t_news.status
	 * @mbggenerated  Wed Sep 07 22:49:06 CST 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news.status
	 * @param status  the value for t_news.status
	 * @mbggenerated  Wed Sep 07 22:49:06 CST 2016
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	public static enum NewsStat implements IntEnum<ComStat> {
		normal("1", "正常"), invalid("0", "失效");

		private final String index;
		private final String name;
		private NewsStat(String index, String name) {
			this.index = index;
			this.name = name;
		}

		public static String getName(String index) {
			for (NewsStat e : NewsStat.values()) {
				if (e.getIndex().equals(index)) {
					return e.name;
				}
			}
			return null;
		}

		public String getName() {
			return name;
		}

		public String getIndex() {
			// TODO Auto-generated method stub
			return index;
		}
	}

	public String getStatDescribe(){
		return NewsStat.getName(this.status);
	}
}