package com.gmzj.entity;

import com.gmzj.entity.Cemetery.ComType;

public class Pic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pic.id
     *
     * @mbggenerated Wed Sep 21 23:15:02 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pic.res_type
     *
     * @mbggenerated Wed Sep 21 23:15:02 CST 2016
     */
    private String resType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pic.res_id
     *
     * @mbggenerated Wed Sep 21 23:15:02 CST 2016
     */
    private Integer resId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pic.seq
     *
     * @mbggenerated Wed Sep 21 23:15:02 CST 2016
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pic.is_main
     *
     * @mbggenerated Wed Sep 21 23:15:02 CST 2016
     */
    private Boolean isMain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pic.img_url
     *
     * @mbggenerated Wed Sep 21 23:15:02 CST 2016
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pic.img_desc
     *
     * @mbggenerated Wed Sep 21 23:15:02 CST 2016
     */
    private String imgDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pic.id
     *
     * @return the value of t_pic.id
     *
     * @mbggenerated Wed Sep 21 23:15:02 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pic.id
     *
     * @param id the value for t_pic.id
     *
     * @mbggenerated Wed Sep 21 23:15:02 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pic.res_type
     *
     * @return the value of t_pic.res_type
     *
     * @mbggenerated Wed Sep 21 23:15:02 CST 2016
     */
    public String getResType() {
        return resType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pic.res_type
     *
     * @param resType the value for t_pic.res_type
     *
     * @mbggenerated Wed Sep 21 23:15:02 CST 2016
     */
    public void setResType(String resType) {
        this.resType = resType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pic.res_id
     *
     * @return the value of t_pic.res_id
     *
     * @mbggenerated Wed Sep 21 23:15:02 CST 2016
     */
    public Integer getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pic.res_id
     *
     * @param resId the value for t_pic.res_id
     *
     * @mbggenerated Wed Sep 21 23:15:02 CST 2016
     */
    public void setResId(Integer resId) {
        this.resId = resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pic.seq
     *
     * @return the value of t_pic.seq
     *
     * @mbggenerated Wed Sep 21 23:15:02 CST 2016
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pic.seq
     *
     * @param seq the value for t_pic.seq
     *
     * @mbggenerated Wed Sep 21 23:15:02 CST 2016
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pic.is_main
     *
     * @return the value of t_pic.is_main
     *
     * @mbggenerated Wed Sep 21 23:15:02 CST 2016
     */
    public Boolean getIsMain() {
        return isMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pic.is_main
     *
     * @param isMain the value for t_pic.is_main
     *
     * @mbggenerated Wed Sep 21 23:15:02 CST 2016
     */
    public void setIsMain(Boolean isMain) {
        this.isMain = isMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pic.img_url
     *
     * @return the value of t_pic.img_url
     *
     * @mbggenerated Wed Sep 21 23:15:02 CST 2016
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pic.img_url
     *
     * @param imgUrl the value for t_pic.img_url
     *
     * @mbggenerated Wed Sep 21 23:15:02 CST 2016
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pic.img_desc
     *
     * @return the value of t_pic.img_desc
     *
     * @mbggenerated Wed Sep 21 23:15:02 CST 2016
     */
    public String getImgDesc() {
        return imgDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pic.img_desc
     *
     * @param imgDesc the value for t_pic.img_desc
     *
     * @mbggenerated Wed Sep 21 23:15:02 CST 2016
     */
    public void setImgDesc(String imgDesc) {
        this.imgDesc = imgDesc;
    }
    
	public static enum picType implements IntEnum<ComType>{
		gm("01","公墓");

		private final String index;
		private final String name;
		private picType(String index, String name) {
			this.index = index;
			this.name = name;
		}

		public static String getName(String index) {
			for (picType e : picType.values()) {
				if (e.getIndex().equals(index)) {
					return e.name;
				}
			}
			return null;
		}

		public String getName() {
			return name;
		}

		public String getIndex() {
			// TODO Auto-generated method stub
			return index;
		}
	}
	
	public String getTypeDescribe(){
		return picType.getName(this.resType);
	}
}