package com.gmzj.entity;

public class RegionMap {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_regionmap.id
	 * @mbggenerated  Tue Aug 16 19:05:41 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_regionmap.name
	 * @mbggenerated  Tue Aug 16 19:05:41 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_regionmap.manageNo
	 * @mbggenerated  Tue Aug 16 19:05:41 CST 2016
	 */
	private String manageno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_regionmap.lvl
	 * @mbggenerated  Tue Aug 16 19:05:41 CST 2016
	 */
	private Integer lvl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_regionmap.id
	 * @return  the value of t_regionmap.id
	 * @mbggenerated  Tue Aug 16 19:05:41 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_regionmap.id
	 * @param id  the value for t_regionmap.id
	 * @mbggenerated  Tue Aug 16 19:05:41 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_regionmap.name
	 * @return  the value of t_regionmap.name
	 * @mbggenerated  Tue Aug 16 19:05:41 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_regionmap.name
	 * @param name  the value for t_regionmap.name
	 * @mbggenerated  Tue Aug 16 19:05:41 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_regionmap.manageNo
	 * @return  the value of t_regionmap.manageNo
	 * @mbggenerated  Tue Aug 16 19:05:41 CST 2016
	 */
	public String getManageno() {
		return manageno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_regionmap.manageNo
	 * @param manageno  the value for t_regionmap.manageNo
	 * @mbggenerated  Tue Aug 16 19:05:41 CST 2016
	 */
	public void setManageno(String manageno) {
		this.manageno = manageno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_regionmap.lvl
	 * @return  the value of t_regionmap.lvl
	 * @mbggenerated  Tue Aug 16 19:05:41 CST 2016
	 */
	public Integer getLvl() {
		return lvl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_regionmap.lvl
	 * @param lvl  the value for t_regionmap.lvl
	 * @mbggenerated  Tue Aug 16 19:05:41 CST 2016
	 */
	public void setLvl(Integer lvl) {
		this.lvl = lvl;
	}
}