package com.gmzj.entity;

public class RegionMap {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_region_map.no
	 * @mbggenerated  Fri Oct 21 22:23:05 CST 2016
	 */
	private String no;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_region_map.name
	 * @mbggenerated  Fri Oct 21 22:23:05 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_region_map.manageNo
	 * @mbggenerated  Fri Oct 21 22:23:05 CST 2016
	 */
	private String manageno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_region_map.lvl
	 * @mbggenerated  Fri Oct 21 22:23:05 CST 2016
	 */
	private Integer lvl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_region_map.no
	 * @return  the value of t_region_map.no
	 * @mbggenerated  Fri Oct 21 22:23:05 CST 2016
	 */
	public String getNo() {
		return no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_region_map.no
	 * @param no  the value for t_region_map.no
	 * @mbggenerated  Fri Oct 21 22:23:05 CST 2016
	 */
	public void setNo(String no) {
		this.no = no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_region_map.name
	 * @return  the value of t_region_map.name
	 * @mbggenerated  Fri Oct 21 22:23:05 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_region_map.name
	 * @param name  the value for t_region_map.name
	 * @mbggenerated  Fri Oct 21 22:23:05 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_region_map.manageNo
	 * @return  the value of t_region_map.manageNo
	 * @mbggenerated  Fri Oct 21 22:23:05 CST 2016
	 */
	public String getManageno() {
		return manageno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_region_map.manageNo
	 * @param manageno  the value for t_region_map.manageNo
	 * @mbggenerated  Fri Oct 21 22:23:05 CST 2016
	 */
	public void setManageno(String manageno) {
		this.manageno = manageno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_region_map.lvl
	 * @return  the value of t_region_map.lvl
	 * @mbggenerated  Fri Oct 21 22:23:05 CST 2016
	 */
	public Integer getLvl() {
		return lvl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_region_map.lvl
	 * @param lvl  the value for t_region_map.lvl
	 * @mbggenerated  Fri Oct 21 22:23:05 CST 2016
	 */
	public void setLvl(Integer lvl) {
		this.lvl = lvl;
	}
}