package com.gmzj.entity;

public class Zone {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.id
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.name
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.introduce
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	private String introduce;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.price
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	private Long price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.company_id
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	private Integer companyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.colours
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	private String colours;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.material
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	private String material;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.type
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.direction
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	private String direction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.ashes_direction
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	private String ashesDirection;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.stat
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	private String stat;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.id
	 * @return  the value of t_zone.id
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.id
	 * @param id  the value for t_zone.id
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.name
	 * @return  the value of t_zone.name
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.name
	 * @param name  the value for t_zone.name
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.introduce
	 * @return  the value of t_zone.introduce
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public String getIntroduce() {
		return introduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.introduce
	 * @param introduce  the value for t_zone.introduce
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public void setIntroduce(String introduce) {
		this.introduce = introduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.price
	 * @return  the value of t_zone.price
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public Long getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.price
	 * @param price  the value for t_zone.price
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public void setPrice(Long price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.company_id
	 * @return  the value of t_zone.company_id
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public Integer getCompanyId() {
		return companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.company_id
	 * @param companyId  the value for t_zone.company_id
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.colours
	 * @return  the value of t_zone.colours
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public String getColours() {
		return colours;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.colours
	 * @param colours  the value for t_zone.colours
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public void setColours(String colours) {
		this.colours = colours;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.material
	 * @return  the value of t_zone.material
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public String getMaterial() {
		return material;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.material
	 * @param material  the value for t_zone.material
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public void setMaterial(String material) {
		this.material = material;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.type
	 * @return  the value of t_zone.type
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.type
	 * @param type  the value for t_zone.type
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.direction
	 * @return  the value of t_zone.direction
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public String getDirection() {
		return direction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.direction
	 * @param direction  the value for t_zone.direction
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public void setDirection(String direction) {
		this.direction = direction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.ashes_direction
	 * @return  the value of t_zone.ashes_direction
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public String getAshesDirection() {
		return ashesDirection;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.ashes_direction
	 * @param ashesDirection  the value for t_zone.ashes_direction
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public void setAshesDirection(String ashesDirection) {
		this.ashesDirection = ashesDirection;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.stat
	 * @return  the value of t_zone.stat
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public String getStat() {
		return stat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.stat
	 * @param stat  the value for t_zone.stat
	 * @mbggenerated  Sun Sep 25 17:02:33 CST 2016
	 */
	public void setStat(String stat) {
		this.stat = stat;
	}
}