package com.gmzj.entity;

public class Zone {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.id
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.name
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.cemetery_id
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	private Integer cemeteryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.code
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.mx_name
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	private String mxName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.orig_price
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	private Long origPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.price
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	private Long price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.material
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	private String material;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.type
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.colours
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	private String colours;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.direction
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	private String direction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.follow_num
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	private Integer followNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.num
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	private String num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.feature
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	private String feature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_zone.stat
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	private String stat;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.id
	 * @return  the value of t_zone.id
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.id
	 * @param id  the value for t_zone.id
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.name
	 * @return  the value of t_zone.name
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.name
	 * @param name  the value for t_zone.name
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.cemetery_id
	 * @return  the value of t_zone.cemetery_id
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public Integer getCemeteryId() {
		return cemeteryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.cemetery_id
	 * @param cemeteryId  the value for t_zone.cemetery_id
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public void setCemeteryId(Integer cemeteryId) {
		this.cemeteryId = cemeteryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.code
	 * @return  the value of t_zone.code
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.code
	 * @param code  the value for t_zone.code
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.mx_name
	 * @return  the value of t_zone.mx_name
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public String getMxName() {
		return mxName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.mx_name
	 * @param mxName  the value for t_zone.mx_name
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public void setMxName(String mxName) {
		this.mxName = mxName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.orig_price
	 * @return  the value of t_zone.orig_price
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public Long getOrigPrice() {
		return origPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.orig_price
	 * @param origPrice  the value for t_zone.orig_price
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public void setOrigPrice(Long origPrice) {
		this.origPrice = origPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.price
	 * @return  the value of t_zone.price
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public Long getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.price
	 * @param price  the value for t_zone.price
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public void setPrice(Long price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.material
	 * @return  the value of t_zone.material
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public String getMaterial() {
		return material;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.material
	 * @param material  the value for t_zone.material
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public void setMaterial(String material) {
		this.material = material;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.type
	 * @return  the value of t_zone.type
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.type
	 * @param type  the value for t_zone.type
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.colours
	 * @return  the value of t_zone.colours
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public String getColours() {
		return colours;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.colours
	 * @param colours  the value for t_zone.colours
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public void setColours(String colours) {
		this.colours = colours;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.direction
	 * @return  the value of t_zone.direction
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public String getDirection() {
		return direction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.direction
	 * @param direction  the value for t_zone.direction
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public void setDirection(String direction) {
		this.direction = direction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.follow_num
	 * @return  the value of t_zone.follow_num
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public Integer getFollowNum() {
		return followNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.follow_num
	 * @param followNum  the value for t_zone.follow_num
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public void setFollowNum(Integer followNum) {
		this.followNum = followNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.num
	 * @return  the value of t_zone.num
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public String getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.num
	 * @param num  the value for t_zone.num
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public void setNum(String num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.feature
	 * @return  the value of t_zone.feature
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public String getFeature() {
		return feature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.feature
	 * @param feature  the value for t_zone.feature
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public void setFeature(String feature) {
		this.feature = feature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_zone.stat
	 * @return  the value of t_zone.stat
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public String getStat() {
		return stat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_zone.stat
	 * @param stat  the value for t_zone.stat
	 * @mbggenerated  Thu Sep 29 15:40:26 CST 2016
	 */
	public void setStat(String stat) {
		this.stat = stat;
	}
}